# Generated by Django 5.2.13 on 2026-04-18 06:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0006_verify_ready_for_cutover'),
    ]

    operations = [
        migrations.AddField(
            model_name='party',
            name='default_billing_cycle',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='parties', to='contacts.customerbillingcycle', verbose_name='Default billing cycle'),
        ),
    ]
