# Generated by Django 5.2.13 on 2026-06-27 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0015_address_split_step3_remove'),
    ]

    operations = [
        migrations.AddField(
            model_name='party',
            name='ext_business_appl_references',
            field=models.JSONField(blank=True, default=dict, verbose_name='External Business Application References'),
        ),
        migrations.AlterField(
            model_name='address',
            name='number',
            field=models.CharField(blank=True, max_length=16, null=True, verbose_name='House Number'),
        ),
        migrations.AlterField(
            model_name='partycontact',
            name='prefix',
            field=models.CharField(blank=True, choices=[('F', 'Company'), ('W', 'Mrs'), ('H', 'Mr'), ('G', 'Ms')], max_length=32, null=True, verbose_name='Prefix'),
        ),
    ]
