# Generated by Django 5.2.7 on 2026-04-12 18:17

from django.db import migrations, models


from koalixcrm.migration_utils import CreateModelIfNotExists
class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        CreateModelIfNotExists(
            name='Account',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('account_number', models.IntegerField(verbose_name='Account Number')),
                ('title', models.CharField(max_length=50, verbose_name='Account Title')),
                ('account_type', models.CharField(choices=[('E', 'Earnings'), ('S', 'Spendings'), ('L', 'Liabilities'), ('A', 'Assets')], max_length=1, verbose_name='Account Type')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('is_open_reliabilities_account', models.BooleanField(verbose_name='Is The Open Liabilities Account')),
                ('is_open_interest_account', models.BooleanField(verbose_name='Is The Open Interests Account')),
                ('is_product_inventory_activa', models.BooleanField(verbose_name='Is a Product Inventory Account')),
                ('is_a_customer_payment_account', models.BooleanField(verbose_name='Is a Customer Payment Account')),
            ],
            options={
                'verbose_name': 'Account',
                'verbose_name_plural': 'Account',
                'ordering': ['account_number'],
            },
        ),
        CreateModelIfNotExists(
            name='AccountingPeriod',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200, verbose_name='Title')),
                ('begin', models.DateField(verbose_name='Begin')),
                ('end', models.DateField(verbose_name='End')),
            ],
            options={
                'verbose_name': 'Accounting Period',
                'verbose_name_plural': 'Accounting Periods',
            },
        ),
        CreateModelIfNotExists(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=20, verbose_name='Amount')),
                ('description', models.CharField(blank=True, max_length=120, null=True, verbose_name='Description')),
                ('booking_date', models.DateTimeField(verbose_name='Booking at')),
                ('date_of_creation', models.DateTimeField(auto_now=True, verbose_name='Created at')),
                ('last_modification', models.DateTimeField(auto_now_add=True, verbose_name='Last modified')),
            ],
            options={
                'verbose_name': 'Booking',
                'verbose_name_plural': 'Bookings',
            },
        ),
        CreateModelIfNotExists(
            name='ProductCategory',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=50, verbose_name='Product Category Title')),
            ],
            options={
                'verbose_name': 'Product Category',
                'verbose_name_plural': 'Product Categories',
            },
        ),
    ]
