# Generated by Django 5.2.13 on 2026-07-04 16:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounting", "0003_tax_and_category_assignments"),
        ("products", "0009_alter_customergrouptransform_product_type_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="productcategoryassignment",
            name="product_type",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="product_category_assignment",
                to="products.product",
                verbose_name="Product",
            ),
        ),
    ]
