# Generated by Django 5.2.13 on 2026-07-04 18:18

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("contacts", "0016_party_ext_business_appl_references_and_more"),
        ("core", "0009_alter_unittransform_product_type"),
        ("products", "0014_productvariant_tracking_mode"),
    ]

    operations = [
        migrations.CreateModel(
            name="Batch",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "batch_number",
                    models.CharField(max_length=100, verbose_name="Batch Number"),
                ),
                (
                    "supplier_lot_number",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="Supplier Lot Number",
                    ),
                ),
                (
                    "production_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="Production Date"
                    ),
                ),
                (
                    "expiry_date",
                    models.DateField(blank=True, null=True, verbose_name="Expiry Date"),
                ),
                (
                    "best_before_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="Best Before Date"
                    ),
                ),
                (
                    "received_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="Received At"
                    ),
                ),
                (
                    "quarantine",
                    models.BooleanField(default=False, verbose_name="Quarantine"),
                ),
                (
                    "notes",
                    models.TextField(blank=True, null=True, verbose_name="Notes"),
                ),
                (
                    "variant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="batches",
                        to="products.productvariant",
                        verbose_name="Product Variant",
                    ),
                ),
                (
                    "workspace",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="core.workspace",
                    ),
                ),
            ],
            options={
                "verbose_name": "Batch",
                "verbose_name_plural": "Batches",
                "db_table": "stock_batch",
                "ordering": ["expiry_date"],
            },
        ),
        migrations.CreateModel(
            name="Location",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "location_type",
                    models.CharField(
                        choices=[
                            ("WAREHOUSE", "Warehouse"),
                            ("ZONE", "Zone"),
                            ("AISLE", "Aisle"),
                            ("RACK", "Rack"),
                            ("SHELF", "Shelf"),
                            ("LAYER", "Layer"),
                            ("BIN", "Bin"),
                            ("VIRTUAL", "Virtual"),
                            ("CUSTOMER_SITE", "Customer Site"),
                        ],
                        max_length=32,
                        verbose_name="Location Type",
                    ),
                ),
                ("code", models.CharField(max_length=100, verbose_name="Code")),
                ("name", models.CharField(max_length=200, verbose_name="Name")),
                (
                    "external_ref",
                    models.CharField(
                        blank=True,
                        help_text="Optional AS/RS address string or barcode plaintext (also the GLN AI (414) resolution target).",
                        max_length=200,
                        null=True,
                        verbose_name="External Reference",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Is Active"),
                ),
                (
                    "last_modification",
                    models.DateTimeField(auto_now=True, verbose_name="Last modified"),
                ),
                (
                    "date_of_creation",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created at"),
                ),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="children",
                        to="stock.location",
                        verbose_name="Parent Location",
                    ),
                ),
                (
                    "workspace",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="core.workspace",
                    ),
                ),
            ],
            options={
                "verbose_name": "Location",
                "verbose_name_plural": "Locations",
                "db_table": "stock_location",
                "ordering": ["code"],
            },
        ),
        migrations.CreateModel(
            name="HandlingUnit",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("sscc", models.CharField(max_length=18, verbose_name="SSCC")),
                (
                    "hu_type",
                    models.CharField(
                        choices=[
                            ("PALLET", "Pallet"),
                            ("CARTON", "Carton"),
                            ("TRAY", "Tray"),
                            ("CAGE", "Cage"),
                            ("OTHER", "Other"),
                        ],
                        max_length=16,
                        verbose_name="Handling Unit Type",
                    ),
                ),
                ("is_open", models.BooleanField(default=True, verbose_name="Is Open")),
                (
                    "last_modification",
                    models.DateTimeField(auto_now=True, verbose_name="Last modified"),
                ),
                (
                    "date_of_creation",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created at"),
                ),
                (
                    "parent_handling_unit",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="child_handling_units",
                        to="stock.handlingunit",
                        verbose_name="Parent Handling Unit",
                    ),
                ),
                (
                    "workspace",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="core.workspace",
                    ),
                ),
                (
                    "location",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="handling_units",
                        to="stock.location",
                        verbose_name="Location",
                    ),
                ),
            ],
            options={
                "verbose_name": "Handling Unit",
                "verbose_name_plural": "Handling Units",
                "db_table": "stock_handlingunit",
                "ordering": ["sscc"],
            },
        ),
        migrations.CreateModel(
            name="RetentionPolicy",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "serial_unit_retention_floor_days",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Minimum number of days a decommissioned SerialUnit must be retained before deletion may be attempted. Null = no configured floor beyond the mandatory decommissioning requirement (ADR-0012 default: forever).",
                        null=True,
                        verbose_name="SerialUnit Retention Floor (days)",
                    ),
                ),
                (
                    "workspace",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="core.workspace",
                    ),
                ),
            ],
            options={
                "verbose_name": "Retention Policy",
                "verbose_name_plural": "Retention Policies",
                "db_table": "stock_retentionpolicy",
            },
        ),
        migrations.CreateModel(
            name="SerialUnit",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "serial_number",
                    models.CharField(max_length=100, verbose_name="Serial Number"),
                ),
                (
                    "global_uid",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="Global UID (ISO/IEC 15459)",
                    ),
                ),
                (
                    "production_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="Production Date"
                    ),
                ),
                (
                    "warranty_expiry",
                    models.DateField(
                        blank=True, null=True, verbose_name="Warranty Expiry"
                    ),
                ),
                (
                    "condition_state",
                    models.CharField(
                        choices=[
                            ("NEW", "New"),
                            ("USED", "Used"),
                            ("DAMAGED", "Damaged"),
                            ("IN_REPAIR", "In Repair"),
                        ],
                        default="NEW",
                        max_length=16,
                        verbose_name="Condition State",
                    ),
                ),
                (
                    "decommissioned_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Decommissioned At"
                    ),
                ),
                (
                    "notes",
                    models.TextField(blank=True, null=True, verbose_name="Notes"),
                ),
                (
                    "batch",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="serial_units",
                        to="stock.batch",
                        verbose_name="Batch",
                    ),
                ),
                (
                    "variant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="serial_units",
                        to="products.productvariant",
                        verbose_name="Product Variant",
                    ),
                ),
                (
                    "workspace",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="core.workspace",
                    ),
                ),
            ],
            options={
                "verbose_name": "Serial Unit",
                "verbose_name_plural": "Serial Units",
                "db_table": "stock_serialunit",
                "ordering": ["serial_number"],
            },
        ),
        migrations.CreateModel(
            name="OnHandRecord",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "owner_type",
                    models.CharField(
                        choices=[
                            ("OWN", "Own"),
                            ("CUSTOMER_CONSIGNMENT", "Customer Consignment"),
                            ("RENTAL", "Rental"),
                        ],
                        default="OWN",
                        max_length=32,
                        verbose_name="Owner Type",
                    ),
                ),
                (
                    "qty_on_hand",
                    models.DecimalField(
                        decimal_places=4,
                        default=Decimal("0"),
                        max_digits=18,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0"))
                        ],
                        verbose_name="Quantity On Hand",
                    ),
                ),
                (
                    "last_modification",
                    models.DateTimeField(auto_now=True, verbose_name="Last modified"),
                ),
                (
                    "date_of_creation",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created at"),
                ),
                (
                    "batch",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="on_hand_records",
                        to="stock.batch",
                        verbose_name="Batch",
                    ),
                ),
                (
                    "handling_unit",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="on_hand_records",
                        to="stock.handlingunit",
                        verbose_name="Handling Unit",
                    ),
                ),
                (
                    "location",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="on_hand_records",
                        to="stock.location",
                        verbose_name="Location",
                    ),
                ),
                (
                    "owner_party",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="owned_stock_records",
                        to="contacts.party",
                        verbose_name="Owner Party",
                    ),
                ),
                (
                    "uom",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="core.unit",
                        verbose_name="Unit of Measure",
                    ),
                ),
                (
                    "variant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="on_hand_records",
                        to="products.productvariant",
                        verbose_name="Product Variant",
                    ),
                ),
                (
                    "workspace",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="core.workspace",
                    ),
                ),
                (
                    "serial_unit",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="on_hand_records",
                        to="stock.serialunit",
                        verbose_name="Serial Unit",
                    ),
                ),
            ],
            options={
                "verbose_name": "On-Hand Record",
                "verbose_name_plural": "On-Hand Records",
                "db_table": "stock_onhandrecord",
                "ordering": ["variant", "location"],
            },
        ),
        migrations.AddIndex(
            model_name="batch",
            index=models.Index(
                fields=["workspace", "variant", "expiry_date"], name="idx_batch_fefo"
            ),
        ),
        migrations.AddConstraint(
            model_name="batch",
            constraint=models.UniqueConstraint(
                fields=("workspace", "variant", "batch_number"),
                name="uniq_batch_number_per_variant",
            ),
        ),
        migrations.AddConstraint(
            model_name="location",
            constraint=models.UniqueConstraint(
                fields=("workspace", "code"), name="uniq_location_code_per_workspace"
            ),
        ),
        migrations.AddConstraint(
            model_name="location",
            constraint=models.UniqueConstraint(
                condition=models.Q(("external_ref__isnull", False)),
                fields=("workspace", "external_ref"),
                name="uniq_location_external_ref_per_workspace",
            ),
        ),
        migrations.AddConstraint(
            model_name="handlingunit",
            constraint=models.UniqueConstraint(
                fields=("workspace", "sscc"),
                name="uniq_handlingunit_sscc_per_workspace",
            ),
        ),
        migrations.AddConstraint(
            model_name="retentionpolicy",
            constraint=models.UniqueConstraint(
                fields=("workspace",), name="uniq_retentionpolicy_per_workspace"
            ),
        ),
        migrations.AddIndex(
            model_name="serialunit",
            index=models.Index(
                condition=models.Q(("decommissioned_at__isnull", True)),
                fields=["workspace"],
                name="idx_serialunit_active",
            ),
        ),
        migrations.AddConstraint(
            model_name="serialunit",
            constraint=models.UniqueConstraint(
                fields=("workspace", "variant", "serial_number"),
                name="uniq_serial_number_per_variant",
            ),
        ),
        migrations.AddConstraint(
            model_name="serialunit",
            constraint=models.UniqueConstraint(
                condition=models.Q(("global_uid__isnull", False)),
                fields=("workspace", "global_uid"),
                name="uniq_serial_global_uid_per_workspace",
            ),
        ),
        migrations.AddIndex(
            model_name="onhandrecord",
            index=models.Index(
                fields=["workspace", "variant", "location"],
                name="idx_onhandrecord_var_loc",
            ),
        ),
        migrations.AddConstraint(
            model_name="onhandrecord",
            constraint=models.UniqueConstraint(
                fields=(
                    "workspace",
                    "variant",
                    "location",
                    "batch",
                    "serial_unit",
                    "owner_type",
                    "owner_party",
                ),
                name="uniq_onhandrecord_key",
            ),
        ),
    ]
