# Generated by Django 5.2.13 on 2026-07-04 18:46

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contacts", "0016_party_ext_business_appl_references_and_more"),
        ("contenttypes", "0002_remove_content_type_name"),
        ("core", "0009_alter_unittransform_product_type"),
        ("products", "0014_productvariant_tracking_mode"),
        ("stock", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="MovementReasonCode",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "code",
                    models.CharField(max_length=100, unique=True, verbose_name="Code"),
                ),
                (
                    "label_de",
                    models.CharField(max_length=200, verbose_name="Label (DE)"),
                ),
                (
                    "label_en",
                    models.CharField(max_length=200, verbose_name="Label (EN)"),
                ),
                (
                    "applies_to_business_steps",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="List of business_step values this reason code is valid for; empty list = valid for all business steps.",
                        verbose_name="Applies To Business Steps",
                    ),
                ),
            ],
            options={
                "verbose_name": "Movement Reason Code",
                "verbose_name_plural": "Movement Reason Codes",
                "db_table": "stock_movementreasoncode",
                "ordering": ["code"],
            },
        ),
        migrations.AddField(
            model_name="retentionpolicy",
            name="stock_movement_retention_floor_days",
            field=models.PositiveIntegerField(
                blank=True,
                help_text="Minimum number of days a StockMovement row must be retained (counted from occurred_at) before deletion may be attempted. Null = no configured floor; default retention is forever (ADR-0011). This is an additive protective lower bound, never an automatic deletion trigger.",
                null=True,
                verbose_name="StockMovement Retention Floor (days)",
            ),
        ),
        migrations.AlterField(
            model_name="onhandrecord",
            name="owner_type",
            field=models.CharField(
                choices=[
                    ("OWN", "Own"),
                    ("CUSTOMER_CONSIGNMENT", "Customer Consignment"),
                    ("RENTAL", "Rental"),
                    ("CUSTOMER_OWNED", "Customer Owned"),
                ],
                default="OWN",
                max_length=32,
                verbose_name="Owner Type",
            ),
        ),
        migrations.CreateModel(
            name="StockReservation",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("SALE", "Sale"),
                            ("RENTAL", "Rental"),
                            ("PROJECT_HOLD", "Project Hold"),
                        ],
                        max_length=16,
                        verbose_name="Kind",
                    ),
                ),
                (
                    "reservation_type",
                    models.CharField(
                        choices=[
                            ("BOOKED", "Booked"),
                            ("RESERVED_FOR_DOCUMENT", "Reserved For Document"),
                        ],
                        default="BOOKED",
                        max_length=32,
                        verbose_name="Reservation Type",
                    ),
                ),
                (
                    "reservation_status",
                    models.CharField(
                        choices=[
                            ("PROVISIONAL", "Provisional"),
                            ("CONFIRMED", "Confirmed"),
                        ],
                        default="PROVISIONAL",
                        max_length=16,
                        verbose_name="Reservation Status",
                    ),
                ),
                (
                    "document_id",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="Document ID"
                    ),
                ),
                (
                    "qty_reserved",
                    models.DecimalField(
                        blank=True,
                        decimal_places=4,
                        help_text="Nullable for serial-number-bound reservations.",
                        max_digits=18,
                        null=True,
                        verbose_name="Quantity Reserved",
                    ),
                ),
                (
                    "rental_start",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Rental Start"
                    ),
                ),
                (
                    "rental_end",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Rental End"
                    ),
                ),
                (
                    "expires_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Expires At"
                    ),
                ),
                (
                    "sent_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="ADR-0010 Amendment OQ-0012 first-SENT-wins concurrency marker: the timestamp this reservation's document-side transition to SENT was recorded, via services/reservation_lifecycle.py:mark_sent(). Null = not yet SENT. Since the offer/order document itself lives outside the stock app (ADR-0010 generic document reference), this field is the service-level FIFO race marker; see Stage 5 deferral notes.",
                        null=True,
                        verbose_name="Sent At",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("ACTIVE", "Active"),
                            ("FULFILLED", "Fulfilled"),
                            ("CANCELLED", "Cancelled"),
                            ("EXPIRED", "Expired"),
                        ],
                        default="ACTIVE",
                        max_length=16,
                        verbose_name="Status",
                    ),
                ),
                (
                    "last_modification",
                    models.DateTimeField(auto_now=True, verbose_name="Last modified"),
                ),
                (
                    "date_of_creation",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created at"),
                ),
                (
                    "batch",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="stock_reservations",
                        to="stock.batch",
                        verbose_name="Batch",
                    ),
                ),
                (
                    "document_type",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="contenttypes.contenttype",
                        verbose_name="Document Type",
                    ),
                ),
                (
                    "location",
                    models.ForeignKey(
                        blank=True,
                        help_text="Null = any location of this tenant.",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="stock_reservations",
                        to="stock.location",
                        verbose_name="Location",
                    ),
                ),
                (
                    "serial_unit",
                    models.ForeignKey(
                        blank=True,
                        help_text="Set for kind = RENTAL and kind = PROJECT_HOLD.",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="stock_reservations",
                        to="stock.serialunit",
                        verbose_name="Serial Unit",
                    ),
                ),
                (
                    "uom",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="core.unit",
                        verbose_name="Unit of Measure",
                    ),
                ),
                (
                    "variant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="stock_reservations",
                        to="products.productvariant",
                        verbose_name="Product Variant",
                    ),
                ),
                (
                    "workspace",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="core.workspace",
                    ),
                ),
            ],
            options={
                "verbose_name": "Stock Reservation",
                "verbose_name_plural": "Stock Reservations",
                "db_table": "stock_stockreservation",
                "ordering": ["-date_of_creation"],
            },
        ),
        migrations.CreateModel(
            name="RentalAssignment",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "document_id",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="Document ID"
                    ),
                ),
                (
                    "rental_start",
                    models.DateTimeField(
                        verbose_name="Rental Start (physical handover)"
                    ),
                ),
                (
                    "return_due_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="Return Due Date"
                    ),
                ),
                (
                    "returned_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Returned At"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("ACTIVE", "Active"),
                            ("RETURNED", "Returned"),
                            ("OVERDUE", "Overdue"),
                            ("WRITTEN_OFF", "Written Off"),
                        ],
                        default="ACTIVE",
                        max_length=16,
                        verbose_name="Status",
                    ),
                ),
                (
                    "condition_at_return",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("NEW", "New"),
                            ("USED", "Used"),
                            ("DAMAGED", "Damaged"),
                            ("IN_REPAIR", "In Repair"),
                        ],
                        max_length=16,
                        null=True,
                        verbose_name="Condition At Return",
                    ),
                ),
                (
                    "last_modification",
                    models.DateTimeField(auto_now=True, verbose_name="Last modified"),
                ),
                (
                    "date_of_creation",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created at"),
                ),
                (
                    "document_type",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="contenttypes.contenttype",
                        verbose_name="Document Type",
                    ),
                ),
                (
                    "on_hand_record",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="rental_assignments",
                        to="stock.onhandrecord",
                        verbose_name="On-Hand Record",
                    ),
                ),
                (
                    "party",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="rental_assignments",
                        to="contacts.party",
                        verbose_name="Renter",
                    ),
                ),
                (
                    "serial_unit",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="rental_assignments",
                        to="stock.serialunit",
                        verbose_name="Serial Unit",
                    ),
                ),
                (
                    "workspace",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="core.workspace",
                    ),
                ),
                (
                    "reservation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="rental_assignments",
                        to="stock.stockreservation",
                        verbose_name="Fulfilled Reservation",
                    ),
                ),
            ],
            options={
                "verbose_name": "Rental Assignment",
                "verbose_name_plural": "Rental Assignments",
                "db_table": "stock_rentalassignment",
                "ordering": ["-rental_start"],
            },
        ),
        migrations.CreateModel(
            name="MovementReasonCodeExtension",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("code", models.CharField(max_length=100, verbose_name="Code")),
                (
                    "label_de",
                    models.CharField(max_length=200, verbose_name="Label (DE)"),
                ),
                (
                    "label_en",
                    models.CharField(max_length=200, verbose_name="Label (EN)"),
                ),
                (
                    "applies_to_business_steps",
                    models.JSONField(
                        blank=True,
                        default=list,
                        verbose_name="Applies To Business Steps",
                    ),
                ),
                (
                    "workspace",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="core.workspace",
                    ),
                ),
            ],
            options={
                "verbose_name": "Movement Reason Code Extension",
                "verbose_name_plural": "Movement Reason Code Extensions",
                "db_table": "stock_movementreasoncodeextension",
                "ordering": ["code"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("workspace", "code"),
                        name="uniq_movementreasoncodeext_per_workspace",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="StockBalance",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "qty_on_hand",
                    models.DecimalField(
                        decimal_places=4,
                        default=Decimal("0"),
                        max_digits=18,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0"))
                        ],
                        verbose_name="Qty On Hand",
                    ),
                ),
                (
                    "qty_booked",
                    models.DecimalField(
                        decimal_places=4,
                        default=Decimal("0"),
                        max_digits=18,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0"))
                        ],
                        verbose_name="Qty Booked",
                    ),
                ),
                (
                    "qty_reserved_for_document",
                    models.DecimalField(
                        decimal_places=4,
                        default=Decimal("0"),
                        max_digits=18,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0"))
                        ],
                        verbose_name="Qty Reserved For Document",
                    ),
                ),
                (
                    "qty_ordered",
                    models.DecimalField(
                        decimal_places=4,
                        default=Decimal("0"),
                        max_digits=18,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0"))
                        ],
                        verbose_name="Qty Ordered",
                    ),
                ),
                (
                    "qty_in_transit",
                    models.DecimalField(
                        decimal_places=4,
                        default=Decimal("0"),
                        max_digits=18,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0"))
                        ],
                        verbose_name="Qty In Transit",
                    ),
                ),
                (
                    "qty_quarantine",
                    models.DecimalField(
                        decimal_places=4,
                        default=Decimal("0"),
                        max_digits=18,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0"))
                        ],
                        verbose_name="Qty Quarantine",
                    ),
                ),
                (
                    "last_modification",
                    models.DateTimeField(auto_now=True, verbose_name="Last modified"),
                ),
                (
                    "date_of_creation",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created at"),
                ),
                (
                    "location",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="stock_balances",
                        to="stock.location",
                        verbose_name="Location",
                    ),
                ),
                (
                    "uom",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="core.unit",
                        verbose_name="Unit of Measure",
                    ),
                ),
                (
                    "variant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="stock_balances",
                        to="products.productvariant",
                        verbose_name="Product Variant",
                    ),
                ),
                (
                    "workspace",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="core.workspace",
                    ),
                ),
            ],
            options={
                "verbose_name": "Stock Balance",
                "verbose_name_plural": "Stock Balances",
                "db_table": "stock_stockbalance",
                "ordering": ["variant", "location"],
                "indexes": [
                    models.Index(
                        fields=["workspace", "variant", "location"],
                        name="idx_stockbalance_var_loc",
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("workspace", "variant", "location"),
                        name="uniq_stockbalance_key",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="StockMovement",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "event_type",
                    models.CharField(
                        choices=[
                            ("OBJECT_EVENT", "Object Event"),
                            ("AGGREGATION_EVENT", "Aggregation Event"),
                            ("TRANSACTION_EVENT", "Transaction Event"),
                            ("TRANSFORMATION_EVENT", "Transformation Event"),
                            ("ASSOCIATION_EVENT", "Association Event"),
                        ],
                        max_length=32,
                        verbose_name="Event Type",
                    ),
                ),
                (
                    "business_step",
                    models.CharField(
                        choices=[
                            ("shipping", "Shipping"),
                            ("receiving", "Receiving"),
                            ("packing", "Packing"),
                            ("picking", "Picking"),
                            ("accepting", "Accepting"),
                            ("inspecting", "Inspecting"),
                            ("scrapping", "Scrapping"),
                            ("returning", "Returning"),
                            ("rental_out", "Rental Out"),
                            ("rental_return", "Rental Return"),
                            ("adjustment", "Adjustment"),
                            ("commissioning", "Commissioning"),
                            ("installing", "Installing"),
                            ("removing", "Removing"),
                            ("repairing", "Repairing"),
                            ("decommissioning", "Decommissioning"),
                            ("inventorying", "Inventorying"),
                        ],
                        max_length=32,
                        verbose_name="Business Step",
                    ),
                ),
                ("occurred_at", models.DateTimeField(verbose_name="Occurred At")),
                (
                    "recorded_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Recorded At"),
                ),
                (
                    "aggregation_group",
                    models.UUIDField(
                        blank=True, null=True, verbose_name="Aggregation Group"
                    ),
                ),
                (
                    "qty",
                    models.DecimalField(
                        blank=True,
                        decimal_places=4,
                        help_text="Null = quantity-less lifecycle event.",
                        max_digits=18,
                        null=True,
                        verbose_name="Quantity",
                    ),
                ),
                (
                    "document_id",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="Document ID"
                    ),
                ),
                (
                    "owner_type",
                    models.CharField(
                        choices=[
                            ("OWN", "Own"),
                            ("CUSTOMER_CONSIGNMENT", "Customer Consignment"),
                            ("RENTAL", "Rental"),
                            ("CUSTOMER_OWNED", "Customer Owned"),
                        ],
                        default="OWN",
                        max_length=32,
                        verbose_name="Owner Type",
                    ),
                ),
                (
                    "disposition",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("in_progress", "In Progress"),
                            ("reserved", "Reserved"),
                            ("in_transit", "In Transit"),
                            ("in_possession", "In Possession"),
                            ("returned", "Returned"),
                            ("destroyed", "Destroyed"),
                        ],
                        max_length=32,
                        null=True,
                        verbose_name="Disposition",
                    ),
                ),
                ("idempotency_key", models.UUIDField(verbose_name="Idempotency Key")),
                (
                    "batch",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="movements",
                        to="stock.batch",
                        verbose_name="Batch",
                    ),
                ),
                (
                    "compensates",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="compensating_movements",
                        to="stock.stockmovement",
                        verbose_name="Compensates",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="stock_movements",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Created By",
                    ),
                ),
                (
                    "destination_location",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="movements_to",
                        to="stock.location",
                        verbose_name="Destination Location",
                    ),
                ),
                (
                    "document_type",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="contenttypes.contenttype",
                        verbose_name="Document Type",
                    ),
                ),
                (
                    "handling_unit",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="movements",
                        to="stock.handlingunit",
                        verbose_name="Handling Unit",
                    ),
                ),
                (
                    "owner_party",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="stock_movements",
                        to="contacts.party",
                        verbose_name="Owner Party",
                    ),
                ),
                (
                    "parent_batch",
                    models.ForeignKey(
                        blank=True,
                        help_text="AGGREGATION_EVENT parent batch when the finished good's tracking_mode = BATCH.",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="child_movements",
                        to="stock.batch",
                        verbose_name="Parent Batch",
                    ),
                ),
                (
                    "parent_serial_unit",
                    models.ForeignKey(
                        blank=True,
                        help_text="AGGREGATION_EVENT parent unit when the finished good's tracking_mode = SERIAL.",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="child_movements",
                        to="stock.serialunit",
                        verbose_name="Parent Serial Unit",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="stock_movements",
                        to="products.product",
                        verbose_name="Product",
                    ),
                ),
                (
                    "reason_code",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="movements",
                        to="stock.movementreasoncode",
                        verbose_name="Reason Code",
                    ),
                ),
                (
                    "serial_unit",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="movements",
                        to="stock.serialunit",
                        verbose_name="Serial Unit",
                    ),
                ),
                (
                    "source_location",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="movements_from",
                        to="stock.location",
                        verbose_name="Source Location",
                    ),
                ),
                (
                    "uom",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="core.unit",
                        verbose_name="Unit of Measure",
                    ),
                ),
                (
                    "variant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="stock_movements",
                        to="products.productvariant",
                        verbose_name="Product Variant",
                    ),
                ),
                (
                    "workspace",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="core.workspace",
                    ),
                ),
            ],
            options={
                "verbose_name": "Stock Movement",
                "verbose_name_plural": "Stock Movements",
                "db_table": "stock_stockmovement",
                "ordering": ["-occurred_at", "-id"],
                "indexes": [
                    models.Index(
                        fields=["workspace", "variant", "occurred_at"],
                        name="idx_stockmovement_var_time",
                    ),
                    models.Index(
                        fields=["workspace", "business_step"],
                        name="idx_stockmovement_bizstep",
                    ),
                    models.Index(
                        fields=["aggregation_group"], name="idx_stockmovement_agggroup"
                    ),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("workspace", "idempotency_key"),
                        name="uniq_stockmovement_idempotency_key",
                    )
                ],
            },
        ),
        migrations.AddIndex(
            model_name="stockreservation",
            index=models.Index(
                fields=["workspace", "variant", "location"],
                name="idx_stockreservation_var_loc",
            ),
        ),
        migrations.AddIndex(
            model_name="stockreservation",
            index=models.Index(
                fields=["workspace", "serial_unit", "status"],
                name="idx_stockreservation_serial_st",
            ),
        ),
        migrations.AddIndex(
            model_name="stockreservation",
            index=models.Index(
                fields=["workspace", "kind", "status"],
                name="idx_stockreservation_kind_st",
            ),
        ),
        migrations.AddIndex(
            model_name="rentalassignment",
            index=models.Index(
                fields=["workspace", "serial_unit", "status"],
                name="idx_rentalassign_serial_status",
            ),
        ),
        migrations.AddIndex(
            model_name="rentalassignment",
            index=models.Index(
                fields=["workspace", "return_due_date"], name="idx_rentalassign_due"
            ),
        ),
    ]
