# Generated by Django 5.2.13 on 2026-07-04 19:12

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contacts", "0016_party_ext_business_appl_references_and_more"),
        ("contenttypes", "0002_remove_content_type_name"),
        ("core", "0009_alter_unittransform_product_type"),
        ("products", "0016_bom_version"),
        ("stock", "0002_movementreasoncode_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="GoodsReceipt",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "external_doc_ref",
                    models.CharField(
                        blank=True,
                        help_text="Supplier's delivery note number.",
                        max_length=200,
                        null=True,
                        verbose_name="External Document Reference",
                    ),
                ),
                (
                    "received_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="Received At"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("DRAFT", "Draft"),
                            ("IN_PROGRESS", "In Progress"),
                            ("COMPLETED", "Completed"),
                            ("CANCELLED", "Cancelled"),
                        ],
                        default="DRAFT",
                        max_length=16,
                        verbose_name="Status",
                    ),
                ),
                (
                    "notes",
                    models.TextField(blank=True, null=True, verbose_name="Notes"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created At"),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="goods_receipts",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Created By",
                    ),
                ),
                (
                    "supplier_party",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="goods_receipts",
                        to="contacts.party",
                        verbose_name="Supplier",
                    ),
                ),
                (
                    "workspace",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="core.workspace",
                    ),
                ),
            ],
            options={
                "verbose_name": "Goods Receipt",
                "verbose_name_plural": "Goods Receipts",
                "db_table": "stock_goodsreceipt",
                "ordering": ["-received_at", "-id"],
            },
        ),
        migrations.CreateModel(
            name="GoodsReceiptLine",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "expected_qty",
                    models.DecimalField(
                        decimal_places=4,
                        max_digits=18,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0"))
                        ],
                        verbose_name="Expected Quantity",
                    ),
                ),
                (
                    "received_qty",
                    models.DecimalField(
                        decimal_places=4,
                        default=Decimal("0"),
                        max_digits=18,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0"))
                        ],
                        verbose_name="Received Quantity",
                    ),
                ),
                (
                    "line_status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("CONFIRMED", "Confirmed"),
                            ("MISMATCHED", "Mismatched"),
                        ],
                        default="PENDING",
                        max_length=16,
                        verbose_name="Line Status",
                    ),
                ),
                (
                    "notes",
                    models.TextField(blank=True, null=True, verbose_name="Notes"),
                ),
                (
                    "batch",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="goods_receipt_lines",
                        to="stock.batch",
                        verbose_name="Batch",
                    ),
                ),
                (
                    "goods_receipt",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lines",
                        to="stock.goodsreceipt",
                        verbose_name="Goods Receipt",
                    ),
                ),
                (
                    "posted_movement",
                    models.ForeignKey(
                        blank=True,
                        help_text="The receiving StockMovement posted for this line when the parent GoodsReceipt completed.",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="goods_receipt_lines",
                        to="stock.stockmovement",
                        verbose_name="Posted Movement",
                    ),
                ),
                (
                    "serial_unit",
                    models.ForeignKey(
                        blank=True,
                        help_text="Minimal serial-capture field for tracking_mode = SERIAL lines.",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="goods_receipt_lines",
                        to="stock.serialunit",
                        verbose_name="Serial Unit",
                    ),
                ),
                (
                    "target_location",
                    models.ForeignKey(
                        blank=True,
                        help_text="Put-away destination; may be filled by the OQ-0015 heuristic suggestion or set manually.",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="goods_receipt_lines",
                        to="stock.location",
                        verbose_name="Target Location",
                    ),
                ),
                (
                    "uom",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="core.unit",
                        verbose_name="Unit of Measure",
                    ),
                ),
                (
                    "variant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="goods_receipt_lines",
                        to="products.productvariant",
                        verbose_name="Product Variant",
                    ),
                ),
                (
                    "workspace",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="core.workspace",
                    ),
                ),
            ],
            options={
                "verbose_name": "Goods Receipt Line",
                "verbose_name_plural": "Goods Receipt Lines",
                "db_table": "stock_goodsreceiptline",
                "ordering": ["goods_receipt_id", "id"],
            },
        ),
        migrations.CreateModel(
            name="ProductionOrder",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "planned_qty",
                    models.DecimalField(
                        decimal_places=4,
                        max_digits=18,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.0001"))
                        ],
                        verbose_name="Planned Quantity",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("DRAFT", "Draft"),
                            ("RELEASED", "Released"),
                            ("IN_PROGRESS", "In Progress"),
                            ("COMPLETED", "Completed"),
                            ("CANCELLED", "Cancelled"),
                        ],
                        default="DRAFT",
                        max_length=16,
                        verbose_name="Status",
                    ),
                ),
                (
                    "planned_start",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Planned Start"
                    ),
                ),
                (
                    "completed_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Completed At"
                    ),
                ),
                (
                    "document_id",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="Document ID"
                    ),
                ),
                (
                    "aggregation_group",
                    models.UUIDField(
                        blank=True, null=True, verbose_name="Aggregation Group"
                    ),
                ),
                (
                    "last_modification",
                    models.DateTimeField(auto_now=True, verbose_name="Last modified"),
                ),
                (
                    "date_of_creation",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created at"),
                ),
                (
                    "bill_of_materials",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="production_orders",
                        to="products.billofmaterials",
                        verbose_name="Bill of Materials",
                    ),
                ),
                (
                    "document_type",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="contenttypes.contenttype",
                        verbose_name="Document Type",
                    ),
                ),
                (
                    "finished_batch",
                    models.ForeignKey(
                        blank=True,
                        help_text="Set on completion when the finished good's tracking_mode = BATCH.",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="produced_by_production_orders",
                        to="stock.batch",
                        verbose_name="Finished Batch",
                    ),
                ),
                (
                    "finished_serial_unit",
                    models.ForeignKey(
                        blank=True,
                        help_text="Set on completion when the finished good's tracking_mode = SERIAL.",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="produced_by_production_orders",
                        to="stock.serialunit",
                        verbose_name="Finished Serial Unit",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="production_orders",
                        to="products.product",
                        verbose_name="Product",
                    ),
                ),
                (
                    "uom",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="core.unit",
                        verbose_name="Unit of Measure",
                    ),
                ),
                (
                    "workspace",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="core.workspace",
                    ),
                ),
            ],
            options={
                "verbose_name": "Production Order",
                "verbose_name_plural": "Production Orders",
                "db_table": "stock_productionorder",
                "ordering": ["-date_of_creation"],
            },
        ),
        migrations.CreateModel(
            name="ProductionOrderComponent",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "planned_qty",
                    models.DecimalField(
                        decimal_places=4,
                        max_digits=18,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0"))
                        ],
                        verbose_name="Planned Quantity",
                    ),
                ),
                (
                    "actual_qty",
                    models.DecimalField(
                        decimal_places=4,
                        default=Decimal("0"),
                        max_digits=18,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0"))
                        ],
                        verbose_name="Actual Quantity",
                    ),
                ),
                (
                    "batch",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="production_order_components",
                        to="stock.batch",
                        verbose_name="Batch",
                    ),
                ),
                (
                    "bom_item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="production_order_components",
                        to="products.bomitem",
                        verbose_name="BOM Item",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="production_order_components",
                        to="products.product",
                        verbose_name="Component Product",
                    ),
                ),
                (
                    "production_order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="components",
                        to="stock.productionorder",
                        verbose_name="Production Order",
                    ),
                ),
                (
                    "reservation",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="production_order_components",
                        to="stock.stockreservation",
                        verbose_name="Stock Reservation",
                    ),
                ),
                (
                    "uom",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="core.unit",
                        verbose_name="Unit of Measure",
                    ),
                ),
                (
                    "variant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="production_order_components",
                        to="products.productvariant",
                        verbose_name="Component Product Variant",
                    ),
                ),
                (
                    "workspace",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="core.workspace",
                    ),
                ),
            ],
            options={
                "verbose_name": "Production Order Component",
                "verbose_name_plural": "Production Order Components",
                "db_table": "stock_productionordercomponent",
                "ordering": ["production_order_id", "id"],
            },
        ),
        migrations.CreateModel(
            name="BillOfMaterialsExplosion",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("bom_version", models.IntegerField(verbose_name="BOM Version")),
                ("depth", models.IntegerField(verbose_name="Depth")),
                (
                    "effective_qty",
                    models.DecimalField(
                        decimal_places=4,
                        max_digits=18,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0"))
                        ],
                        verbose_name="Effective Quantity",
                    ),
                ),
                (
                    "computed_at",
                    models.DateTimeField(auto_now=True, verbose_name="Computed At"),
                ),
                (
                    "bill_of_materials",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="explosion_rows",
                        to="products.billofmaterials",
                        verbose_name="Bill of Materials",
                    ),
                ),
                (
                    "bom_item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="explosion_rows",
                        to="products.bomitem",
                        verbose_name="Leaf BOM Item",
                    ),
                ),
                (
                    "uom",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="core.unit",
                        verbose_name="Unit of Measure",
                    ),
                ),
                (
                    "workspace",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="core.workspace",
                    ),
                ),
            ],
            options={
                "verbose_name": "Bill of Materials Explosion",
                "verbose_name_plural": "Bill of Materials Explosions",
                "db_table": "stock_billofmaterialsexplosion",
                "ordering": ["bill_of_materials_id", "depth", "id"],
                "indexes": [
                    models.Index(
                        fields=["workspace", "bill_of_materials", "bom_version"],
                        name="idx_bomexplosion_bom_version",
                    )
                ],
            },
        ),
        migrations.AddIndex(
            model_name="goodsreceipt",
            index=models.Index(
                fields=["workspace", "status"], name="idx_goodsreceipt_status"
            ),
        ),
        migrations.AddIndex(
            model_name="goodsreceipt",
            index=models.Index(
                fields=["workspace", "supplier_party"], name="idx_goodsreceipt_supplier"
            ),
        ),
        migrations.AddIndex(
            model_name="goodsreceiptline",
            index=models.Index(
                fields=["workspace", "variant"], name="idx_goodsreceiptline_variant"
            ),
        ),
        migrations.AddIndex(
            model_name="goodsreceiptline",
            index=models.Index(
                fields=["workspace", "line_status"], name="idx_goodsreceiptline_status"
            ),
        ),
        migrations.AddIndex(
            model_name="productionorder",
            index=models.Index(
                fields=["workspace", "status"], name="idx_productionorder_status"
            ),
        ),
        migrations.AddIndex(
            model_name="productionorder",
            index=models.Index(
                fields=["workspace", "product"], name="idx_productionorder_product"
            ),
        ),
        migrations.AddIndex(
            model_name="productionordercomponent",
            index=models.Index(
                fields=["workspace", "variant"], name="idx_prodordercomp_variant"
            ),
        ),
    ]
