# -*- coding: utf-8 -*-
from koalixcrm.accounting.serializers.account_serializer import AccountJSONSerializer as AccountJSONSerializer, OptionAccountJSONSerializer as OptionAccountJSONSerializer
from koalixcrm.accounting.serializers.accounting_period_serializer import AccountingPeriodJSONSerializer as AccountingPeriodJSONSerializer, OptionAccountingPeriodJSONSerializer as OptionAccountingPeriodJSONSerializer
from koalixcrm.accounting.serializers.booking_serializer import BookingJSONSerializer as BookingJSONSerializer
from koalixcrm.accounting.serializers.product_category_serializer import ProductCategoryJSONSerializer as ProductCategoryJSONSerializer, ProductCategoryMinimalJSONSerializer as ProductCategoryMinimalJSONSerializer
