# Generated by Django 5.2.7 on 2026-04-12 18:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


from koalixcrm.migration_utils import CreateModelIfNotExists
class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounting', '0001_initial'),
        ('contacts', '0001_initial'),
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        CreateModelIfNotExists(
            name='ProductType',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('title', models.CharField(max_length=200, verbose_name='Title')),
                ('product_type_identifier', models.CharField(blank=True, max_length=200, null=True, verbose_name='Product Number')),
                ('last_modification', models.DateTimeField(auto_now=True, verbose_name='Last modified')),
                ('date_of_creation', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('accounting_product_category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounting.productcategory', verbose_name='Accounting Product Category')),
                ('last_modified_by', models.ForeignKey(blank=True, limit_choices_to={'is_staff': True}, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Last modified by')),
                ('default_unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.unit', verbose_name='Unit')),
                ('tax', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.tax')),
            ],
            options={
                'verbose_name': 'Product Type',
                'verbose_name_plural': 'Product Types',
                'db_table': 'crm_producttype',
            },
        ),
        CreateModelIfNotExists(
            name='Product',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('identifier', models.CharField(blank=True, max_length=200, null=True, verbose_name='Product Number')),
                ('product_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.producttype', verbose_name='Product Type')),
            ],
            options={
                'db_table': 'crm_product',
            },
        ),
        CreateModelIfNotExists(
            name='CustomerGroupTransform',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('factor', models.DecimalField(decimal_places=2, max_digits=17, verbose_name='Factor between From and To Customer Group')),
                ('from_customer_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='db_reltransfromfromcustomergroup', to='contacts.customergroup', verbose_name='From Customer Group')),
                ('to_customer_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='db_reltransfromtocustomergroup', to='contacts.customergroup', verbose_name='To Customer Group')),
                ('product_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.producttype', verbose_name='Product Type')),
            ],
            options={
                'verbose_name': 'Customer Group Price Transform',
                'verbose_name_plural': 'Customer Group Price Transforms',
                'db_table': 'crm_customergrouptransform',
            },
        ),
        CreateModelIfNotExists(
            name='Price',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=17, verbose_name='Price Per Unit')),
                ('valid_from', models.DateField(blank=True, null=True, verbose_name='Valid from')),
                ('valid_until', models.DateField(blank=True, null=True, verbose_name='Valid until')),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.currency', verbose_name='Currency')),
                ('customer_group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contacts.customergroup', verbose_name='Customer Group')),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.unit', verbose_name='Unit')),
            ],
            options={
                'verbose_name': 'Price',
                'verbose_name_plural': 'Prices',
                'db_table': 'crm_price',
            },
        ),
        CreateModelIfNotExists(
            name='ProductPrice',
            fields=[
                ('price_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='products.price')),
                ('product_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.producttype', verbose_name='Product Type')),
            ],
            options={
                'verbose_name': 'Product Price',
                'verbose_name_plural': 'Product Prices',
                'db_table': 'crm_productprice',
            },
            bases=('products.price',),
        ),
    ]
