# Generated by Django 5.2.13 on 2026-07-04 16:41

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0008_product_catalog_backbone"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customergrouptransform",
            name="product_type",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="products.product",
                verbose_name="Product",
            ),
        ),
        migrations.AlterField(
            model_name="productprice",
            name="product_type",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="products.product",
                verbose_name="Product",
            ),
        ),
        migrations.AlterField(
            model_name="productvariant",
            name="dimensions_height_m",
            field=models.DecimalField(
                blank=True,
                decimal_places=4,
                max_digits=12,
                null=True,
                validators=[django.core.validators.MinValueValidator(0)],
                verbose_name="Height (m)",
            ),
        ),
        migrations.AlterField(
            model_name="productvariant",
            name="dimensions_length_m",
            field=models.DecimalField(
                blank=True,
                decimal_places=4,
                max_digits=12,
                null=True,
                validators=[django.core.validators.MinValueValidator(0)],
                verbose_name="Length (m)",
            ),
        ),
        migrations.AlterField(
            model_name="productvariant",
            name="dimensions_width_m",
            field=models.DecimalField(
                blank=True,
                decimal_places=4,
                max_digits=12,
                null=True,
                validators=[django.core.validators.MinValueValidator(0)],
                verbose_name="Width (m)",
            ),
        ),
        migrations.AlterField(
            model_name="productvariant",
            name="weight_kg",
            field=models.DecimalField(
                blank=True,
                decimal_places=4,
                max_digits=12,
                null=True,
                validators=[django.core.validators.MinValueValidator(0)],
                verbose_name="Weight (kg)",
            ),
        ),
    ]
