# Generated by Django 5.2.13 on 2026-07-04 17:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        ("core", "0009_alter_unittransform_product_type"),
        ("products", "0009_alter_customergrouptransform_product_type_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Classification",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("code", models.SlugField(unique=True, verbose_name="Code")),
                ("name", models.CharField(max_length=200, verbose_name="Name")),
                (
                    "description",
                    models.TextField(blank=True, null=True, verbose_name="Description"),
                ),
            ],
            options={
                "verbose_name": "Classification",
                "verbose_name_plural": "Classifications",
                "db_table": "products_classification",
                "ordering": ["code"],
            },
        ),
        migrations.CreateModel(
            name="AttributeGroup",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "scope",
                    models.CharField(
                        choices=[
                            ("GLOBAL", "Global"),
                            ("WORKSPACE", "Workspace"),
                            ("INHERITED", "Inherited"),
                        ],
                        default="WORKSPACE",
                        max_length=32,
                        verbose_name="Scope",
                    ),
                ),
                ("key", models.SlugField(max_length=100, verbose_name="Key")),
                ("name", models.CharField(max_length=200, verbose_name="Name")),
                (
                    "description",
                    models.TextField(blank=True, null=True, verbose_name="Description"),
                ),
                (
                    "workspace",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="core.workspace",
                        verbose_name="Workspace",
                    ),
                ),
            ],
            options={
                "verbose_name": "Attribute Group",
                "verbose_name_plural": "Attribute Groups",
                "db_table": "products_attributegroup",
                "ordering": ["key"],
            },
        ),
        migrations.CreateModel(
            name="AttributeDefinition",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "scope",
                    models.CharField(
                        choices=[
                            ("GLOBAL", "Global"),
                            ("WORKSPACE", "Workspace"),
                            ("INHERITED", "Inherited"),
                        ],
                        default="WORKSPACE",
                        max_length=32,
                        verbose_name="Scope",
                    ),
                ),
                ("key", models.SlugField(max_length=100, verbose_name="Key")),
                (
                    "canonical_key",
                    models.CharField(
                        blank=True,
                        help_text="ADR-0018 koalix.* canonical vocabulary key this attribute backs, if any.",
                        max_length=100,
                        null=True,
                        verbose_name="Canonical Key",
                    ),
                ),
                ("label", models.CharField(max_length=200, verbose_name="Label")),
                (
                    "data_type",
                    models.CharField(
                        choices=[
                            ("string", "String"),
                            ("int", "Integer"),
                            ("decimal", "Decimal"),
                            ("bool", "Boolean"),
                            ("enum", "Enum"),
                            ("measure", "Measure (decimal + unit)"),
                            ("reference", "Reference"),
                            ("json", "JSON"),
                        ],
                        max_length=16,
                        verbose_name="Data Type",
                    ),
                ),
                ("order", models.PositiveIntegerField(default=0, verbose_name="Order")),
                (
                    "min_value",
                    models.DecimalField(
                        blank=True,
                        decimal_places=6,
                        max_digits=20,
                        null=True,
                        verbose_name="Min Value",
                    ),
                ),
                (
                    "max_value",
                    models.DecimalField(
                        blank=True,
                        decimal_places=6,
                        max_digits=20,
                        null=True,
                        verbose_name="Max Value",
                    ),
                ),
                (
                    "regex",
                    models.CharField(
                        blank=True, max_length=500, null=True, verbose_name="Regex"
                    ),
                ),
                (
                    "enum_values",
                    models.JSONField(
                        blank=True, default=list, verbose_name="Enum Values"
                    ),
                ),
                (
                    "is_localized",
                    models.BooleanField(default=False, verbose_name="Is Localized"),
                ),
                (
                    "is_required",
                    models.BooleanField(default=False, verbose_name="Is Required"),
                ),
                (
                    "is_multivalued",
                    models.BooleanField(default=False, verbose_name="Is Multivalued"),
                ),
                (
                    "unit",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="core.unit",
                        verbose_name="Unit",
                    ),
                ),
                (
                    "workspace",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="core.workspace",
                        verbose_name="Workspace",
                    ),
                ),
                (
                    "group",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="attribute_definitions",
                        to="products.attributegroup",
                        verbose_name="Attribute Group",
                    ),
                ),
            ],
            options={
                "verbose_name": "Attribute Definition",
                "verbose_name_plural": "Attribute Definitions",
                "db_table": "products_attributedefinition",
                "ordering": ["key"],
            },
        ),
        migrations.CreateModel(
            name="AttributeSet",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=200, verbose_name="Name")),
                (
                    "description",
                    models.TextField(blank=True, null=True, verbose_name="Description"),
                ),
                (
                    "kind",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("SERVICE", "Service"),
                            ("TRADING_GOOD", "Trading Good"),
                            ("MANUFACTURED_GOOD", "Manufactured Good"),
                            ("KIT", "Kit"),
                            ("RAW_MATERIAL", "Raw Material"),
                        ],
                        max_length=32,
                        null=True,
                        verbose_name="Kind",
                    ),
                ),
                (
                    "product_family",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attribute_sets",
                        to="products.productfamily",
                        verbose_name="Product Family",
                    ),
                ),
                (
                    "workspace",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="core.workspace",
                    ),
                ),
            ],
            options={
                "verbose_name": "Attribute Set",
                "verbose_name_plural": "Attribute Sets",
                "db_table": "products_attributeset",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="AttributeSetDefault",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "default_value",
                    models.JSONField(
                        blank=True, null=True, verbose_name="Default Value"
                    ),
                ),
                (
                    "attribute_definition",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="set_defaults",
                        to="products.attributedefinition",
                        verbose_name="Attribute Definition",
                    ),
                ),
                (
                    "attribute_set",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="defaults",
                        to="products.attributeset",
                        verbose_name="Attribute Set",
                    ),
                ),
                (
                    "workspace",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="core.workspace",
                    ),
                ),
            ],
            options={
                "verbose_name": "Attribute Set Default",
                "verbose_name_plural": "Attribute Set Defaults",
                "db_table": "products_attributesetdefault",
                "ordering": ["attribute_set_id", "attribute_definition_id"],
            },
        ),
        migrations.CreateModel(
            name="AttributeSetGroup",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("order", models.PositiveIntegerField(default=0, verbose_name="Order")),
                (
                    "attribute_group",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="set_groups",
                        to="products.attributegroup",
                    ),
                ),
                (
                    "attribute_set",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="set_groups",
                        to="products.attributeset",
                    ),
                ),
            ],
            options={
                "verbose_name": "Attribute Set Group",
                "verbose_name_plural": "Attribute Set Groups",
                "db_table": "products_attributesetgroup",
                "ordering": ["attribute_set", "order"],
            },
        ),
        migrations.AddField(
            model_name="attributeset",
            name="attribute_groups",
            field=models.ManyToManyField(
                related_name="attribute_sets",
                through="products.AttributeSetGroup",
                to="products.attributegroup",
                verbose_name="Attribute Groups",
            ),
        ),
        migrations.CreateModel(
            name="AttributeValidationRule",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("key", models.SlugField(max_length=100, verbose_name="Key")),
                ("name", models.CharField(max_length=200, verbose_name="Name")),
                ("order", models.PositiveIntegerField(default=0, verbose_name="Order")),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Is Active"),
                ),
                (
                    "condition",
                    models.JSONField(
                        help_text='e.g. {"attribute": "gloss_level", "op": "eq", "value": "matt"}',
                        verbose_name="Condition",
                    ),
                ),
                (
                    "then",
                    models.JSONField(
                        help_text='e.g. {"attribute": "voc_content", "requirement": "required"} or {"attributes": ["a", "b"], "requirement": "mutually_exclusive"}',
                        verbose_name="Then",
                    ),
                ),
                (
                    "attribute_set",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="validation_rules",
                        to="products.attributeset",
                        verbose_name="Attribute Set",
                    ),
                ),
                (
                    "workspace",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="core.workspace",
                    ),
                ),
            ],
            options={
                "verbose_name": "Attribute Validation Rule",
                "verbose_name_plural": "Attribute Validation Rules",
                "db_table": "products_attributevalidationrule",
                "ordering": ["attribute_set_id", "order"],
            },
        ),
        migrations.CreateModel(
            name="ClassificationNode",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("code", models.CharField(max_length=100, verbose_name="Code")),
                ("name", models.CharField(max_length=200, verbose_name="Name")),
                (
                    "level",
                    models.PositiveSmallIntegerField(default=0, verbose_name="Level"),
                ),
                (
                    "classification",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="nodes",
                        to="products.classification",
                        verbose_name="Classification",
                    ),
                ),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="children",
                        to="products.classificationnode",
                        verbose_name="Parent Node",
                    ),
                ),
            ],
            options={
                "verbose_name": "Classification Node",
                "verbose_name_plural": "Classification Nodes",
                "db_table": "products_classificationnode",
                "ordering": ["classification", "code"],
            },
        ),
        migrations.AddField(
            model_name="attributeset",
            name="classification_node",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="attribute_sets",
                to="products.classificationnode",
                verbose_name="Classification Node",
            ),
        ),
        migrations.CreateModel(
            name="ProductAttributeMapping",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "source_standard",
                    models.CharField(
                        help_text="e.g. eclass, gpc, etim, unspsc",
                        max_length=50,
                        verbose_name="Source Standard",
                    ),
                ),
                (
                    "source_attribute_id",
                    models.CharField(
                        help_text="Native attribute identifier of the source standard, e.g. an eCl@ss IRDI.",
                        max_length=200,
                        verbose_name="Source Attribute Id",
                    ),
                ),
                (
                    "canonical_key",
                    models.CharField(
                        help_text="ADR-0018 koalix.* canonical vocabulary key this source maps to.",
                        max_length=100,
                        verbose_name="Canonical Key",
                    ),
                ),
                (
                    "transform",
                    models.JSONField(
                        blank=True,
                        help_text="Optional data-driven unit conversion / value mapping formula.",
                        null=True,
                        verbose_name="Transform",
                    ),
                ),
                (
                    "workspace",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="core.workspace",
                    ),
                ),
            ],
            options={
                "verbose_name": "Product Attribute Mapping",
                "verbose_name_plural": "Product Attribute Mappings",
                "db_table": "products_productattributemapping",
                "ordering": ["source_standard", "source_attribute_id"],
            },
        ),
        migrations.CreateModel(
            name="ProductAttributeInt",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "imported_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Imported At"
                    ),
                ),
                (
                    "last_modification",
                    models.DateTimeField(auto_now=True, verbose_name="Last modified"),
                ),
                (
                    "date_of_creation",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created at"),
                ),
                ("value", models.BigIntegerField(verbose_name="Value")),
                (
                    "attribute_definition",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_values",
                        to="products.attributedefinition",
                        verbose_name="Attribute Definition",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_values",
                        to="products.product",
                        verbose_name="Product",
                    ),
                ),
                (
                    "variant",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_values",
                        to="products.productvariant",
                        verbose_name="Variant",
                    ),
                ),
                (
                    "workspace",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="core.workspace",
                    ),
                ),
                (
                    "source_mapping",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="products.productattributemapping",
                        verbose_name="Source Mapping",
                    ),
                ),
            ],
            options={
                "verbose_name": "Product Attribute (Int)",
                "verbose_name_plural": "Product Attributes (Int)",
                "db_table": "products_productattributeint",
            },
        ),
        migrations.CreateModel(
            name="ProductAttributeEnum",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "imported_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Imported At"
                    ),
                ),
                (
                    "last_modification",
                    models.DateTimeField(auto_now=True, verbose_name="Last modified"),
                ),
                (
                    "date_of_creation",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created at"),
                ),
                ("value", models.CharField(max_length=200, verbose_name="Value")),
                (
                    "attribute_definition",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_values",
                        to="products.attributedefinition",
                        verbose_name="Attribute Definition",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_values",
                        to="products.product",
                        verbose_name="Product",
                    ),
                ),
                (
                    "variant",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_values",
                        to="products.productvariant",
                        verbose_name="Variant",
                    ),
                ),
                (
                    "workspace",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="core.workspace",
                    ),
                ),
                (
                    "source_mapping",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="products.productattributemapping",
                        verbose_name="Source Mapping",
                    ),
                ),
            ],
            options={
                "verbose_name": "Product Attribute (Enum)",
                "verbose_name_plural": "Product Attributes (Enum)",
                "db_table": "products_productattributeenum",
            },
        ),
        migrations.CreateModel(
            name="ProductAttributeDecimal",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "imported_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Imported At"
                    ),
                ),
                (
                    "last_modification",
                    models.DateTimeField(auto_now=True, verbose_name="Last modified"),
                ),
                (
                    "date_of_creation",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created at"),
                ),
                (
                    "value",
                    models.DecimalField(
                        decimal_places=6, max_digits=20, verbose_name="Value"
                    ),
                ),
                (
                    "attribute_definition",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_values",
                        to="products.attributedefinition",
                        verbose_name="Attribute Definition",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_values",
                        to="products.product",
                        verbose_name="Product",
                    ),
                ),
                (
                    "unit",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="core.unit",
                        verbose_name="Unit",
                    ),
                ),
                (
                    "variant",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_values",
                        to="products.productvariant",
                        verbose_name="Variant",
                    ),
                ),
                (
                    "workspace",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="core.workspace",
                    ),
                ),
                (
                    "source_mapping",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="products.productattributemapping",
                        verbose_name="Source Mapping",
                    ),
                ),
            ],
            options={
                "verbose_name": "Product Attribute (Decimal)",
                "verbose_name_plural": "Product Attributes (Decimal)",
                "db_table": "products_productattributedecimal",
            },
        ),
        migrations.CreateModel(
            name="ProductAttributeBool",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "imported_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Imported At"
                    ),
                ),
                (
                    "last_modification",
                    models.DateTimeField(auto_now=True, verbose_name="Last modified"),
                ),
                (
                    "date_of_creation",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created at"),
                ),
                ("value", models.BooleanField(verbose_name="Value")),
                (
                    "attribute_definition",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_values",
                        to="products.attributedefinition",
                        verbose_name="Attribute Definition",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_values",
                        to="products.product",
                        verbose_name="Product",
                    ),
                ),
                (
                    "variant",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_values",
                        to="products.productvariant",
                        verbose_name="Variant",
                    ),
                ),
                (
                    "workspace",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="core.workspace",
                    ),
                ),
                (
                    "source_mapping",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="products.productattributemapping",
                        verbose_name="Source Mapping",
                    ),
                ),
            ],
            options={
                "verbose_name": "Product Attribute (Bool)",
                "verbose_name_plural": "Product Attributes (Bool)",
                "db_table": "products_productattributebool",
            },
        ),
        migrations.CreateModel(
            name="ProductAttributeMirror",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "data",
                    models.JSONField(blank=True, default=dict, verbose_name="Data"),
                ),
                (
                    "last_modification",
                    models.DateTimeField(auto_now=True, verbose_name="Last modified"),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attribute_mirrors",
                        to="products.product",
                        verbose_name="Product",
                    ),
                ),
                (
                    "variant",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attribute_mirrors",
                        to="products.productvariant",
                        verbose_name="Variant",
                    ),
                ),
                (
                    "workspace",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="core.workspace",
                    ),
                ),
            ],
            options={
                "verbose_name": "Product Attribute Mirror",
                "verbose_name_plural": "Product Attribute Mirrors",
                "db_table": "products_productattributemirror",
                "ordering": ["product_id", "variant_id"],
            },
        ),
        migrations.CreateModel(
            name="ProductAttributeReference",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "imported_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Imported At"
                    ),
                ),
                (
                    "last_modification",
                    models.DateTimeField(auto_now=True, verbose_name="Last modified"),
                ),
                (
                    "date_of_creation",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created at"),
                ),
                (
                    "object_id",
                    models.PositiveBigIntegerField(verbose_name="Lookup Entity Id"),
                ),
                (
                    "attribute_definition",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_values",
                        to="products.attributedefinition",
                        verbose_name="Attribute Definition",
                    ),
                ),
                (
                    "content_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="contenttypes.contenttype",
                        verbose_name="Lookup Entity Type",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_values",
                        to="products.product",
                        verbose_name="Product",
                    ),
                ),
                (
                    "source_mapping",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="products.productattributemapping",
                        verbose_name="Source Mapping",
                    ),
                ),
                (
                    "variant",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_values",
                        to="products.productvariant",
                        verbose_name="Variant",
                    ),
                ),
                (
                    "workspace",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="core.workspace",
                    ),
                ),
            ],
            options={
                "verbose_name": "Product Attribute (Reference)",
                "verbose_name_plural": "Product Attributes (Reference)",
                "db_table": "products_productattributereference",
            },
        ),
        migrations.CreateModel(
            name="ProductAttributeString",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "imported_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Imported At"
                    ),
                ),
                (
                    "last_modification",
                    models.DateTimeField(auto_now=True, verbose_name="Last modified"),
                ),
                (
                    "date_of_creation",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created at"),
                ),
                ("value", models.TextField(verbose_name="Value")),
                (
                    "attribute_definition",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_values",
                        to="products.attributedefinition",
                        verbose_name="Attribute Definition",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_values",
                        to="products.product",
                        verbose_name="Product",
                    ),
                ),
                (
                    "source_mapping",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="products.productattributemapping",
                        verbose_name="Source Mapping",
                    ),
                ),
                (
                    "variant",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_values",
                        to="products.productvariant",
                        verbose_name="Variant",
                    ),
                ),
                (
                    "workspace",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="core.workspace",
                    ),
                ),
            ],
            options={
                "verbose_name": "Product Attribute (String)",
                "verbose_name_plural": "Product Attributes (String)",
                "db_table": "products_productattributestring",
            },
        ),
        migrations.CreateModel(
            name="ProductClassification",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "date_of_creation",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created at"),
                ),
                (
                    "classification_node",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="product_classifications",
                        to="products.classificationnode",
                        verbose_name="Classification Node",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="classifications",
                        to="products.product",
                        verbose_name="Product",
                    ),
                ),
                (
                    "workspace",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="core.workspace",
                    ),
                ),
            ],
            options={
                "verbose_name": "Product Classification",
                "verbose_name_plural": "Product Classifications",
                "db_table": "products_productclassification",
                "ordering": ["product_id", "classification_node_id"],
            },
        ),
        migrations.AddConstraint(
            model_name="attributegroup",
            constraint=models.UniqueConstraint(
                condition=models.Q(("workspace__isnull", False)),
                fields=("workspace", "key"),
                name="unique_attribute_group_key_per_workspace",
            ),
        ),
        migrations.AddConstraint(
            model_name="attributegroup",
            constraint=models.UniqueConstraint(
                condition=models.Q(("workspace__isnull", True)),
                fields=("key",),
                name="unique_attribute_group_key_global",
            ),
        ),
        migrations.AddConstraint(
            model_name="attributedefinition",
            constraint=models.UniqueConstraint(
                condition=models.Q(("workspace__isnull", False)),
                fields=("workspace", "key"),
                name="unique_attribute_definition_key_per_workspace",
            ),
        ),
        migrations.AddConstraint(
            model_name="attributedefinition",
            constraint=models.UniqueConstraint(
                condition=models.Q(("workspace__isnull", True)),
                fields=("key",),
                name="unique_attribute_definition_key_global",
            ),
        ),
        migrations.AddConstraint(
            model_name="attributesetdefault",
            constraint=models.UniqueConstraint(
                fields=("attribute_set", "attribute_definition"),
                name="unique_attribute_set_default",
            ),
        ),
        migrations.AddConstraint(
            model_name="attributesetgroup",
            constraint=models.UniqueConstraint(
                fields=("attribute_set", "attribute_group"),
                name="unique_attribute_set_group",
            ),
        ),
        migrations.AddConstraint(
            model_name="attributevalidationrule",
            constraint=models.UniqueConstraint(
                fields=("attribute_set", "key"),
                name="unique_attribute_validation_rule_key",
            ),
        ),
        migrations.AddConstraint(
            model_name="classificationnode",
            constraint=models.UniqueConstraint(
                fields=("classification", "code"),
                name="unique_classification_node_code",
            ),
        ),
        migrations.AddConstraint(
            model_name="productattributemapping",
            constraint=models.UniqueConstraint(
                fields=("workspace", "source_standard", "source_attribute_id"),
                name="unique_product_attribute_mapping_source",
            ),
        ),
        migrations.AddIndex(
            model_name="productattributeint",
            index=models.Index(
                fields=["product", "variant", "attribute_definition"],
                name="pa_int_pvad_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="productattributeint",
            constraint=models.UniqueConstraint(
                fields=("product", "variant", "attribute_definition"),
                name="unique_pa_int_pvad",
            ),
        ),
        migrations.AddIndex(
            model_name="productattributeenum",
            index=models.Index(
                fields=["product", "variant", "attribute_definition"],
                name="pa_enum_pvad_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="productattributeenum",
            constraint=models.UniqueConstraint(
                fields=("product", "variant", "attribute_definition"),
                name="unique_pa_enum_pvad",
            ),
        ),
        migrations.AddIndex(
            model_name="productattributedecimal",
            index=models.Index(
                fields=["product", "variant", "attribute_definition"],
                name="pa_decimal_pvad_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="productattributedecimal",
            constraint=models.UniqueConstraint(
                fields=("product", "variant", "attribute_definition"),
                name="unique_pa_decimal_pvad",
            ),
        ),
        migrations.AddIndex(
            model_name="productattributebool",
            index=models.Index(
                fields=["product", "variant", "attribute_definition"],
                name="pa_bool_pvad_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="productattributebool",
            constraint=models.UniqueConstraint(
                fields=("product", "variant", "attribute_definition"),
                name="unique_pa_bool_pvad",
            ),
        ),
        migrations.AddConstraint(
            model_name="productattributemirror",
            constraint=models.UniqueConstraint(
                fields=("product", "variant"), name="unique_attribute_mirror_pv"
            ),
        ),
        migrations.AddIndex(
            model_name="productattributereference",
            index=models.Index(
                fields=["product", "variant", "attribute_definition"],
                name="pa_reference_pvad_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="productattributereference",
            constraint=models.UniqueConstraint(
                fields=("product", "variant", "attribute_definition"),
                name="unique_pa_reference_pvad",
            ),
        ),
        migrations.AddIndex(
            model_name="productattributestring",
            index=models.Index(
                fields=["product", "variant", "attribute_definition"],
                name="pa_string_pvad_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="productattributestring",
            constraint=models.UniqueConstraint(
                fields=("product", "variant", "attribute_definition"),
                name="unique_pa_string_pvad",
            ),
        ),
        migrations.AddConstraint(
            model_name="productclassification",
            constraint=models.UniqueConstraint(
                fields=("product", "classification_node"),
                name="unique_product_classification_node",
            ),
        ),
    ]
