# Generated by Django 5.2.13 on 2026-07-04 17:44

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contacts", "0016_party_ext_business_appl_references_and_more"),
        ("core", "0009_alter_unittransform_product_type"),
        ("products", "0010_classification_attributegroup_attributedefinition_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="productprice",
            name="variant",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="prices",
                to="products.productvariant",
                verbose_name="Product Variant",
            ),
        ),
        migrations.AlterField(
            model_name="productprice",
            name="product_type",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="products.product",
                verbose_name="Product (legacy, removed in migration 0013)",
            ),
        ),
        migrations.CreateModel(
            name="BillOfMaterials",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "name",
                    models.CharField(
                        blank=True, max_length=200, null=True, verbose_name="Name"
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, null=True, verbose_name="Description"),
                ),
                (
                    "last_modification",
                    models.DateTimeField(auto_now=True, verbose_name="Last modified"),
                ),
                (
                    "date_of_creation",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created at"),
                ),
                (
                    "product",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bill_of_materials",
                        to="products.product",
                        verbose_name="Product",
                    ),
                ),
                (
                    "workspace",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="core.workspace",
                    ),
                ),
            ],
            options={
                "verbose_name": "Bill of Materials",
                "verbose_name_plural": "Bills of Materials",
                "db_table": "products_billofmaterials",
                "ordering": ["product_id"],
            },
        ),
        migrations.CreateModel(
            name="BomItem",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "quantity",
                    models.DecimalField(
                        decimal_places=4,
                        max_digits=17,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.0001"))
                        ],
                        verbose_name="Quantity",
                    ),
                ),
                (
                    "scrap_pct",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=5,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0")),
                            django.core.validators.MaxValueValidator(Decimal("100")),
                        ],
                        verbose_name="Scrap Percentage",
                    ),
                ),
                (
                    "last_modification",
                    models.DateTimeField(auto_now=True, verbose_name="Last modified"),
                ),
                (
                    "date_of_creation",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created at"),
                ),
                (
                    "alternative_component",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="alternative_in_bom_items",
                        to="products.product",
                        verbose_name="Alternative Component",
                    ),
                ),
                (
                    "bill_of_materials",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="products.billofmaterials",
                        verbose_name="Bill of Materials",
                    ),
                ),
                (
                    "component_product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="used_in_bom_items",
                        to="products.product",
                        verbose_name="Component Product",
                    ),
                ),
                (
                    "default_component_variant",
                    models.ForeignKey(
                        blank=True,
                        help_text="Non-binding suggestion for the picking/reservation form; must be a variant of `component_product`.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="default_in_bom_items",
                        to="products.productvariant",
                        verbose_name="Default Component Variant",
                    ),
                ),
                (
                    "unit",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core.unit",
                        verbose_name="Unit",
                    ),
                ),
                (
                    "workspace",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="core.workspace",
                    ),
                ),
            ],
            options={
                "verbose_name": "BOM Item",
                "verbose_name_plural": "BOM Items",
                "db_table": "products_bomitem",
                "ordering": ["bill_of_materials_id", "id"],
            },
        ),
        migrations.CreateModel(
            name="PriceList",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=200, verbose_name="Name")),
                (
                    "channel",
                    models.CharField(
                        blank=True,
                        help_text="Optional channel identifier (e.g. 'webshop', 'wholesale').",
                        max_length=100,
                        null=True,
                        verbose_name="Channel",
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, null=True, verbose_name="Description"),
                ),
                (
                    "last_modification",
                    models.DateTimeField(auto_now=True, verbose_name="Last modified"),
                ),
                (
                    "date_of_creation",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created at"),
                ),
                (
                    "party_group",
                    models.ForeignKey(
                        blank=True,
                        help_text="Optional customer segment this price list applies to.",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="price_lists",
                        to="contacts.partygroup",
                        verbose_name="Customer Segment",
                    ),
                ),
                (
                    "workspace",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="core.workspace",
                    ),
                ),
            ],
            options={
                "verbose_name": "Price List",
                "verbose_name_plural": "Price Lists",
                "db_table": "products_pricelist",
                "ordering": ["name"],
            },
        ),
        migrations.AddField(
            model_name="productprice",
            name="price_list",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="prices",
                to="products.pricelist",
                verbose_name="Price List",
            ),
        ),
        migrations.CreateModel(
            name="ProductPassport",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "passport_data",
                    models.JSONField(
                        blank=True, default=dict, verbose_name="Passport Data"
                    ),
                ),
                (
                    "last_modification",
                    models.DateTimeField(auto_now=True, verbose_name="Last modified"),
                ),
                (
                    "date_of_creation",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created at"),
                ),
                (
                    "product",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="passport",
                        to="products.product",
                        verbose_name="Product",
                    ),
                ),
                (
                    "workspace",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="core.workspace",
                    ),
                ),
            ],
            options={
                "verbose_name": "Product Passport",
                "verbose_name_plural": "Product Passports",
                "db_table": "products_productpassport",
                "ordering": ["product_id"],
            },
        ),
        migrations.CreateModel(
            name="ProductSupply",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "supplier_sku",
                    models.CharField(
                        blank=True,
                        max_length=200,
                        null=True,
                        verbose_name="Supplier SKU",
                    ),
                ),
                (
                    "lead_time_days",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="Lead Time (working days)"
                    ),
                ),
                (
                    "moq",
                    models.DecimalField(
                        blank=True,
                        decimal_places=4,
                        max_digits=17,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.0001"))
                        ],
                        verbose_name="Minimum Order Quantity",
                    ),
                ),
                (
                    "purchase_price",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=17,
                        null=True,
                        verbose_name="Purchase Price",
                    ),
                ),
                (
                    "last_modification",
                    models.DateTimeField(auto_now=True, verbose_name="Last modified"),
                ),
                (
                    "date_of_creation",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created at"),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="supplies",
                        to="products.product",
                        verbose_name="Product",
                    ),
                ),
                (
                    "purchase_currency",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="core.currency",
                        verbose_name="Purchase Currency",
                    ),
                ),
                (
                    "supplier",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="product_supplies",
                        to="contacts.party",
                        verbose_name="Supplier",
                    ),
                ),
                (
                    "workspace",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="core.workspace",
                    ),
                ),
            ],
            options={
                "verbose_name": "Product Supply",
                "verbose_name_plural": "Product Supplies",
                "db_table": "products_productsupply",
                "ordering": ["product_id"],
            },
        ),
        migrations.CreateModel(
            name="ServiceProfile",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "billing_model",
                    models.CharField(
                        choices=[
                            ("fixed", "Fixed"),
                            ("hourly", "Hourly"),
                            ("subscription", "Subscription"),
                            ("tiered", "Tiered"),
                        ],
                        max_length=32,
                        verbose_name="Billing Model",
                    ),
                ),
                (
                    "default_duration",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="Default Duration (minutes)"
                    ),
                ),
                ("deliverable", models.TextField(verbose_name="Deliverable")),
                (
                    "sla_reference",
                    models.CharField(
                        blank=True,
                        max_length=500,
                        null=True,
                        verbose_name="SLA Reference",
                    ),
                ),
                (
                    "last_modification",
                    models.DateTimeField(auto_now=True, verbose_name="Last modified"),
                ),
                (
                    "date_of_creation",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created at"),
                ),
                (
                    "product",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="service_profile",
                        to="products.product",
                        verbose_name="Product",
                    ),
                ),
                (
                    "workspace",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="core.workspace",
                    ),
                ),
            ],
            options={
                "verbose_name": "Service Profile",
                "verbose_name_plural": "Service Profiles",
                "db_table": "products_serviceprofile",
                "ordering": ["product_id"],
            },
        ),
        migrations.CreateModel(
            name="UnitOfMeasureConversion",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "factor",
                    models.DecimalField(
                        decimal_places=10,
                        max_digits=20,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("1E-10"))
                        ],
                        verbose_name="Conversion Factor",
                    ),
                ),
                (
                    "last_modification",
                    models.DateTimeField(auto_now=True, verbose_name="Last modified"),
                ),
                (
                    "date_of_creation",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created at"),
                ),
                (
                    "from_unit",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="core.unit",
                        verbose_name="From Unit",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="uom_conversions",
                        to="products.product",
                        verbose_name="Product",
                    ),
                ),
                (
                    "to_unit",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="core.unit",
                        verbose_name="To Unit",
                    ),
                ),
                (
                    "workspace",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="core.workspace",
                    ),
                ),
            ],
            options={
                "verbose_name": "Unit of Measure Conversion",
                "verbose_name_plural": "Unit of Measure Conversions",
                "db_table": "products_unitofmeasureconversion",
                "ordering": ["product_id"],
            },
        ),
        migrations.AddConstraint(
            model_name="pricelist",
            constraint=models.UniqueConstraint(
                fields=("workspace", "name"), name="pricelist_unique_name_per_workspace"
            ),
        ),
        migrations.AddConstraint(
            model_name="productsupply",
            constraint=models.UniqueConstraint(
                fields=("product", "supplier"),
                name="productsupply_unique_product_supplier",
            ),
        ),
        migrations.AddConstraint(
            model_name="unitofmeasureconversion",
            constraint=models.UniqueConstraint(
                fields=("product", "from_unit", "to_unit"),
                name="uom_conversion_unique_product_from_to",
            ),
        ),
    ]
