# Generated by Django 5.2.13 on 2026-07-04 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0013_finalize_productprice_variant_rekey"),
    ]

    operations = [
        migrations.AddField(
            model_name="productvariant",
            name="tracking_mode",
            field=models.CharField(
                choices=[("NONE", "None"), ("BATCH", "Batch"), ("SERIAL", "Serial")],
                default="NONE",
                help_text="ADR-0009/ADR-0012/ADR-0021: NONE, BATCH (requires stock.Batch) or SERIAL (requires stock.SerialUnit).",
                max_length=16,
                verbose_name="Tracking Mode",
            ),
        ),
    ]
