# Generated by Django 5.2.13 on 2026-07-04 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0014_productvariant_tracking_mode"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="kit_mode",
            field=models.CharField(
                choices=[
                    ("EXPLODE_ON_PICK", "Explode On Pick"),
                    ("PREASSEMBLE", "Preassemble"),
                ],
                default="EXPLODE_ON_PICK",
                help_text="ADR-0014: only evaluated by the application layer for kind = KIT.",
                max_length=16,
                verbose_name="Kit Mode",
            ),
        ),
    ]
