# Generated by Django 5.2.13 on 2026-07-04 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0015_kit_mode"),
    ]

    operations = [
        migrations.AddField(
            model_name="billofmaterials",
            name="version",
            field=models.PositiveIntegerField(
                default=1,
                help_text="ADR-0014: bumped whenever a BomItem of this BOM is created, changed or removed; the BOM-explosion snapshot pins the version it was computed against so the pick-time path can detect staleness.",
                verbose_name="Version",
            ),
        ),
    ]
