# -*- coding: utf-8 -*-

from koalixcrm.products.models.attribute_definition import *
from koalixcrm.products.models.attribute_group import *
from koalixcrm.products.models.attribute_set import *
from koalixcrm.products.models.attribute_set_default import *
from koalixcrm.products.models.attribute_validation_rule import *
from koalixcrm.products.models.bill_of_materials import *
from koalixcrm.products.models.bom_item import *
from koalixcrm.products.models.classification import *
from koalixcrm.products.models.customer_group_transform import *
from koalixcrm.products.models.price import *
from koalixcrm.products.models.price_list import *
from koalixcrm.products.models.product import *
from koalixcrm.products.models.product_attribute_bool import *
from koalixcrm.products.models.product_attribute_decimal import *
from koalixcrm.products.models.product_attribute_enum import *
from koalixcrm.products.models.product_attribute_int import *
from koalixcrm.products.models.product_attribute_mapping import *
from koalixcrm.products.models.product_attribute_mirror import *
from koalixcrm.products.models.product_attribute_reference import *
from koalixcrm.products.models.product_attribute_string import *
from koalixcrm.products.models.product_classification import *
from koalixcrm.products.models.product_family import *
from koalixcrm.products.models.product_media import *
from koalixcrm.products.models.product_passport import *
from koalixcrm.products.models.product_price import *
from koalixcrm.products.models.product_supply import *
from koalixcrm.products.models.product_translation import *
from koalixcrm.products.models.product_variant import *
from koalixcrm.products.models.service_profile import *
from koalixcrm.products.models.unit_of_measure_conversion import *
