# -*- coding: utf-8 -*-


from koalixcrm.djangoUserExtension.models import *
from koalixcrm.djangoUserExtension.user_extension.user_extension import UserExtension, OptionUserExtension
from koalixcrm.djangoUserExtension.user_extension.template_set import TemplateSet, OptionTemplateSet
from koalixcrm.djangoUserExtension.user_extension.document_template import InvoiceTemplate, OptionInvoiceTemplate
from koalixcrm.djangoUserExtension.user_extension.document_template import QuoteTemplate, OptionQuoteTemplate
from koalixcrm.djangoUserExtension.user_extension.document_template import DeliveryNoteTemplate, OptionDeliveryNoteTemplate
from koalixcrm.djangoUserExtension.user_extension.document_template import PaymentReminderTemplate, OptionPaymentReminderTemplate
from koalixcrm.djangoUserExtension.user_extension.document_template import PurchaseOrderTemplate, OptionPurchaseOrderTemplate
from koalixcrm.djangoUserExtension.user_extension.document_template import ProfitLossStatementTemplate, OptionProfitLossStatementTemplate
from koalixcrm.djangoUserExtension.user_extension.document_template import BalanceSheetTemplate, OptionBalanceSheetTemplate


admin.site.register(UserExtension, OptionUserExtension)
admin.site.register(TemplateSet, OptionTemplateSet)
admin.site.register(InvoiceTemplate, OptionInvoiceTemplate)
admin.site.register(QuoteTemplate, OptionQuoteTemplate)
admin.site.register(DeliveryNoteTemplate, OptionDeliveryNoteTemplate)
admin.site.register(PaymentReminderTemplate, OptionPaymentReminderTemplate)
admin.site.register(PurchaseOrderTemplate, OptionPurchaseOrderTemplate)
admin.site.register(PurchaseConfirmationTemplate, OptionPurchaseConfirmationTemplate)
admin.site.register(ProfitLossStatementTemplate, OptionProfitLossStatementTemplate)
admin.site.register(BalanceSheetTemplate, OptionBalanceSheetTemplate)
admin.site.register(MonthlyProjectSummaryTemplate, OptionProjectSummaryTemplate)
