# Generated by Django 5.2.7 on 2026-04-12 18:17

import django.db.models.deletion
import filebrowser.fields
from django.db import migrations, models


from koalixcrm.migration_utils import CreateModelIfNotExists, AddFieldIfNotExists
class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contract_object_management', '0001_initial'),
        ('products', '0001_initial'),
    ]

    operations = [
        CreateModelIfNotExists(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contract_object_management.contract', verbose_name='Subscription Type')),
            ],
            options={
                'verbose_name': 'Subscription',
                'verbose_name_plural': 'Subscriptions',
            },
        ),
        CreateModelIfNotExists(
            name='SubscriptionEvent',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('event_date', models.DateField(blank=True, null=True, verbose_name='Event Date')),
                ('event', models.CharField(choices=[('O', 'Offered'), ('C', 'Canceled'), ('S', 'Signed')], max_length=1, verbose_name='Event')),
                ('subscriptions', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='subscriptions.subscription', verbose_name='Subscription')),
            ],
            options={
                'verbose_name': 'Subscription Event',
                'verbose_name_plural': 'Subscription Events',
            },
        ),
        CreateModelIfNotExists(
            name='SubscriptionType',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('cancellation_period', models.IntegerField(blank=True, null=True, verbose_name='Cancellation Period (months)')),
                ('automatic_contract_extension', models.IntegerField(blank=True, null=True, verbose_name='Automatic Contract Extension (months)')),
                ('automatic_contract_extension_reminder', models.IntegerField(blank=True, null=True, verbose_name='Automatic Contract Extension Reminder (days)')),
                ('minimum_duration', models.IntegerField(blank=True, null=True, verbose_name='Minimum Contract Duration')),
                ('payment_interval', models.IntegerField(blank=True, null=True, verbose_name='Payment Interval (days)')),
                ('contract_document', filebrowser.fields.FileBrowseField(blank=True, max_length=200, null=True, verbose_name='Contract Documents')),
                ('product_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.producttype', verbose_name='Product Type')),
            ],
            options={
                'verbose_name': 'Subscription Type',
                'verbose_name_plural': 'Subscription Types',
            },
        ),
        AddFieldIfNotExists(
            model_name='subscription',
            name='subscription_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='subscriptions.subscriptiontype', verbose_name='Subscription Type'),
        ),
    ]
