# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-10-13 22:13
from __future__ import unicode_literals

from django.db import migrations, models
from filebrowser.fields import FileBrowseField
from django.db.models.indexes import Index


def fill_subscription_type_backup_table(apps, schema_editor):
    Subscription = apps.get_model("subscriptions", "Subscription")
    SubscriptionType = apps.get_model("subscriptions", "SubscriptionType")
    SubscriptionTypeBackup = apps.get_model("subscriptions", "SubscriptionTypeBackup")
    db_alias = schema_editor.connection.alias
    all_subscription_types = SubscriptionType.objects.using(db_alias).all()
    for subscription_type in all_subscription_types:
        subscription_type_backup = SubscriptionTypeBackup.objects.using(db_alias).create(
            cancellation_period=subscription_type.cancellation_period,
            automatic_contract_extension=subscription_type.automatic_contract_extension,
            automatic_contract_extension_reminder=subscription_type.automatic_contract_extension_reminder,
            minimum_duration=subscription_type.minimum_duration,
            payment_interval=subscription_type.payment_interval,
            contract_document=subscription_type.contract_document,
            description=subscription_type.description,
            title=subscription_type.title,
            product_number=subscription_type.product_number,
            default_unit=subscription_type.default_unit,
            date_of_creation=subscription_type.date_of_creation,
            last_modification=subscription_type.last_modification,
            last_modified_by=subscription_type.last_modified_by,
            tax=subscription_type.tax,
            accounting_product_categorie=subscription_type.accounting_product_categorie)
        subscription_type_backup.save()
        subscriptions = Subscription.objects.using(db_alias).filter(subscription_type=subscription_type)
        for subscription in subscriptions:
            subscription.subscription_type_backup = subscription.subscription_type.id
            subscription.save()


def reverse_func(apps, schema_editor):
    return 1


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0047_work_worked_hours'),
        ('subscriptions', '0003_auto_20171110_1732'),
    ]

    operations = [
        migrations.AddField(
            model_name='Subscription',
            name='subscription_type_backup',
            field=models.IntegerField(blank=True, null=True, verbose_name='Subscription Type Backup'),
        ),
        migrations.CreateModel(
            name='SubscriptionTypeBackup',
            fields=[
                ('cancellation_period', models.IntegerField(verbose_name="Cancellation Period (months)",
                                                            blank=True,
                                                            null=True)),
                ('automatic_contract_extension', models.IntegerField(
                    verbose_name="Automatic Contract Extension (months)",
                    blank=True,
                    null=True)),
                ('automatic_contract_extension_reminder', models.IntegerField(
                    verbose_name="Automatic Contract Extension Reminder (days)",
                    blank=True,
                    null=True)),
                ('minimum_duration', models.IntegerField(verbose_name="Minimum Contract Duration",
                                                         blank=True,
                                                         null=True)),
                ('payment_interval', models.IntegerField(verbose_name="Payment Interval (days)",
                                                         blank=True,
                                                         null=True)),
                ('contract_document', FileBrowseField(verbose_name="Contract Documents",
                                                      blank=True,
                                                      null=True,
                                                      max_length=200)),
                ('description', models.TextField(verbose_name="Description",
                                                 null=True,
                                                 blank=True)),
                ('title', models.CharField(verbose_name="Title",
                                           max_length=200)),
                ('product_number', models.IntegerField(verbose_name="Product Number")),
                ('default_unit', models.ForeignKey("crm.Unit",
                                                   verbose_name="Unit")),
                ('date_of_creation', models.DateTimeField(verbose_name="Created at",
                                                          auto_now_add=True)),
                ('last_modification', models.DateTimeField(verbose_name="Last modified",
                                                           auto_now=True)),
                ('last_modified_by', models.ForeignKey('auth.User',
                                                       limit_choices_to={'is_staff': True},
                                                       verbose_name="Last modified by",
                                                       null=True,
                                                       blank="True")),
                ('tax', models.ForeignKey("crm.Tax",
                                          blank=False)),
                ('accounting_product_categorie', models.ForeignKey('accounting.ProductCategorie',
                                                                   verbose_name="Accounting Product Categorie",
                                                                   null=True,
                                                                   blank="True")),
            ],
            options={
                'verbose_name': 'SubscriptionTypeBackup',
                'verbose_name_plural': 'SubscriptionTypeBackups',
            },
        ),
        migrations.RunPython(fill_subscription_type_backup_table, reverse_func),
        migrations.RemoveField(
            model_name='subscription',
            name='subscription_type',
        ),
        migrations.DeleteModel('SubscriptionType'),
    ]
