# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-10-12 20:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0048_auto_20181012_2056'),
        ('subscriptions', '0003_auto_20171110_1732'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subscription',
            old_name='subscriptiontype',
            new_name='subscription_type',
        ),
        migrations.RenameField(
            model_name='subscriptionevent',
            old_name='eventdate',
            new_name='event_date',
        ),
        migrations.RenameField(
            model_name='subscriptiontype',
            old_name='automaticContractExtension',
            new_name='automatic_contract_extension',
        ),
        migrations.RenameField(
            model_name='subscriptiontype',
            old_name='contractDocument',
            new_name='contract_document',
        ),
        migrations.RenameField(
            model_name='subscriptiontype',
            old_name='minimumDuration',
            new_name='minimum_duration',
        ),
        migrations.RemoveField(
            model_name='subscriptiontype',
            name='automaticContractExtensionReminder',
        ),
        migrations.RemoveField(
            model_name='subscriptiontype',
            name='cancelationPeriod',
        ),
        migrations.RemoveField(
            model_name='subscriptiontype',
            name='paymentIntervall',
        ),
        migrations.RemoveField(
            model_name='subscriptiontype',
            name='product_ptr',
        ),
        migrations.AddField(
            model_name='subscriptiontype',
            name='automatic_contract_extension_reminder',
            field=models.IntegerField(blank=True, null=True, verbose_name='Automatic Contract Extension Reminder (days)'),
        ),
        migrations.AddField(
            model_name='subscriptiontype',
            name='cancellation_period',
            field=models.IntegerField(blank=True, null=True, verbose_name='Cancellation Period (months)'),
        ),
        migrations.AddField(
            model_name='subscriptiontype',
            name='payment_interval',
            field=models.IntegerField(blank=True, null=True, verbose_name='Payment Interval (days)'),
        ),
        migrations.AddField(
            model_name='subscriptiontype',
            name='producttype_ptr',
            field=models.OneToOneField(auto_created=True, default=1, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='crm.ProductType'),
            preserve_default=False,
        ),
    ]
