# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-20 16:40
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0024_auto_20180122_2121'),
    ]

    operations = [
        migrations.AlterField(
            model_name='position',
            name='position_number',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Position Number'),
        ),
    ]
