# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-21 14:02
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0030_auto_20180221_1354'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customerpersonassociation',
            name='customer',
        ),
        migrations.RemoveField(
            model_name='customerpersonassociation',
            name='person',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='people',
        ),
        migrations.RemoveField(
            model_name='person',
            name='customers',
        ),
        migrations.DeleteModel(
            name='CustomerPersonAssociation',
        ),
    ]
