# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-21 14:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0031_auto_20180221_1402'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='people',
            field=models.ManyToManyField(blank=True, to='crm.Person', verbose_name='Has contact'),
        ),
    ]
