# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-21 15:55
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0033_auto_20180221_1539'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='call',
            name='customer',
        ),
        migrations.RemoveField(
            model_name='call',
            name='supplier',
        ),
    ]
