# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-21 16:04
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0034_auto_20180221_1555'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='call',
            name='template_set',
        ),
    ]
