# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-06-19 19:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0034_genericprojectlink'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='short_description',
        ),
        migrations.AddField(
            model_name='task',
            name='title',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Title'),
        ),
    ]
