# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-21 18:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0037_customer_no_phones'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='role',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Role'),
        ),
    ]
