# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-21 19:16
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0038_person_role'),
    ]

    operations = [
        migrations.RenameField(
            model_name='callforcontact',
            old_name='person',
            new_name='company',
        ),
        migrations.RenameField(
            model_name='emailaddressforcontact',
            old_name='person',
            new_name='company',
        ),
        migrations.RenameField(
            model_name='phoneaddressforcontact',
            old_name='person',
            new_name='company',
        ),
        migrations.RenameField(
            model_name='postaladdressforcontact',
            old_name='person',
            new_name='company',
        ),
    ]
