# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-07-24 16:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0039_auto_20180702_1635'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tracks', to='crm.Project', verbose_name='Project'),
        ),
    ]
