# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-21 19:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0039_auto_20180221_1916'),
    ]

    operations = [
        migrations.AddField(
            model_name='callforcontact',
            name='cperson',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='crm.Person'),
        ),
    ]
