# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-21 20:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0040_callforcontact_cperson'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='customers',
            field=models.ManyToManyField(blank=True, to='crm.Customer', verbose_name='Works at'),
        ),
        migrations.AlterField(
            model_name='callforcontact',
            name='cperson',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='crm.Person', verbose_name='Person'),
        ),
    ]
