# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-21 20:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0041_auto_20180221_2048'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerPersonAssociation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.RemoveField(
            model_name='customer',
            name='people',
        ),
        migrations.RemoveField(
            model_name='person',
            name='customers',
        ),
        migrations.AddField(
            model_name='customerpersonassociation',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='person_association', to='crm.Customer'),
        ),
        migrations.AddField(
            model_name='customerpersonassociation',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customer_association', to='crm.Person'),
        ),
    ]
