# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-21 20:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0042_auto_20180221_2056'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='people',
            field=models.ManyToManyField(blank=True, through='crm.CustomerPersonAssociation', to='crm.Person', verbose_name='Has contact'),
        ),
        migrations.AddField(
            model_name='person',
            name='customers',
            field=models.ManyToManyField(blank=True, through='crm.CustomerPersonAssociation', to='crm.Customer', verbose_name='Works at'),
        ),
    ]
