# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-21 21:08
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0043_auto_20180221_2057'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='people',
        ),
    ]
