# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-21 21:10
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0044_remove_customer_people'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='customers',
        ),
    ]
