# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-22 11:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0046_auto_20180221_2112'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactpersonassociation',
            name='contact',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='person_association', to='crm.Contact'),
        ),
        migrations.AlterField(
            model_name='contactpersonassociation',
            name='person',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='contact_association', to='crm.Person'),
        ),
    ]
