# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-22 13:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0047_auto_20180222_1101'),
    ]

    operations = [
        migrations.CreateModel(
            name='PhoneSystem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('system_model', models.CharField(blank=True, max_length=200, null=True, verbose_name='Model')),
                ('year', models.IntegerField(blank=True, null=True, verbose_name='Year of installation')),
                ('n_phones_ana', models.IntegerField(blank=True, null=True, verbose_name='Analog phones')),
                ('n_phones_dig', models.IntegerField(blank=True, null=True, verbose_name='Digital phones')),
                ('n_ext_lines', models.IntegerField(blank=True, null=True, verbose_name='External lines')),
            ],
            options={
                'verbose_name': 'Phone System',
                'verbose_name_plural': 'Phone System',
            },
        ),
        migrations.RemoveField(
            model_name='customer',
            name='no_phones',
        ),
        migrations.CreateModel(
            name='PhoneSystemForCustomer',
            fields=[
                ('phonesystem_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='crm.PhoneSystem')),
                ('service_type', models.CharField(blank=True, max_length=100, null=True, verbose_name='Service Type')),
                ('expire_date', models.DateTimeField(blank=True, verbose_name='Expire Date')),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='supplier_association', to='crm.Customer')),
                ('supplier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='customer_association', to='crm.Supplier')),
            ],
            bases=('crm.phonesystem',),
        ),
    ]
