# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-09-13 19:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0048_auto_20180913_2009'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resource',
            name='default_resource_price',
        ),
        migrations.AlterField(
            model_name='estimation',
            name='estimation_from',
            field=models.DateField(verbose_name='Estimation From'),
        ),
        migrations.AlterField(
            model_name='estimation',
            name='estimation_to',
            field=models.DateField(verbose_name='Estimation To'),
        ),
    ]
