# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-09-13 19:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0049_auto_20180913_2124'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='estimation',
            name='estimation_status',
        ),
    ]
