# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-22 17:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0050_auto_20180222_1554'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phonesystemforcustomer',
            name='expire_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Expire Date'),
        ),
    ]
