# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-09-13 19:51
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0050_remove_estimation_estimation_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='estimation',
            name='estimation_type',
        ),
    ]
