# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-23 16:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0051_auto_20180222_1740'),
    ]

    operations = [
        migrations.AlterField(
            model_name='call',
            name='status',
            field=models.CharField(choices=[('P', 'Planned'), ('D', 'Delayed'), ('R', 'ToRecall'), ('A', 'Failed'), ('S', 'Success')], default='P', max_length=1, verbose_name='Status'),
        ),
    ]
