# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-09-14 16:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0051_remove_estimation_estimation_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='EstimationStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250, verbose_name='Title')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Text')),
                ('is_obsolete', models.BooleanField(verbose_name='Status represents estimation is obsolete')),
            ],
            options={
                'verbose_name': 'Estimation Status',
                'verbose_name_plural': 'Estimation Status',
            },
        ),
        migrations.AlterModelOptions(
            name='agreement',
            options={'verbose_name': 'Agreement', 'verbose_name_plural': 'Agreements'},
        ),
        migrations.RenameField(
            model_name='estimation',
            old_name='estimation_amount',
            new_name='amount',
        ),
        migrations.RenameField(
            model_name='estimation',
            old_name='estimation_from',
            new_name='date_from',
        ),
        migrations.RenameField(
            model_name='estimation',
            old_name='estimation_to',
            new_name='date_until',
        ),
        migrations.AddField(
            model_name='estimation',
            name='status',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='crm.EstimationStatus'),
            preserve_default=False,
        ),
    ]
