# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-09-14 16:56
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0052_auto_20180914_1853'),
    ]

    operations = [
        migrations.RenameField(
            model_name='agreement',
            old_name='agreement_amount',
            new_name='amount',
        ),
        migrations.RenameField(
            model_name='agreement',
            old_name='agreement_from',
            new_name='date_from',
        ),
        migrations.RenameField(
            model_name='agreement',
            old_name='agreement_to',
            new_name='date_until',
        ),
        migrations.RenameField(
            model_name='agreement',
            old_name='agreement_status',
            new_name='status',
        ),
        migrations.RenameField(
            model_name='agreement',
            old_name='agreement_type',
            new_name='type',
        ),
    ]
