# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-24 16:14
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0052_auto_20180223_1609'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='addressline1',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='addressline2',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='country',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='state',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='town',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='zipcode',
        ),
    ]
