# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-09-14 17:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0053_auto_20180914_1856'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='default_reporting_period_duration',
            field=models.DurationField(blank=True, null=True, verbose_name='Duration of Default Reporting Period'),
        ),
    ]
