# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-09-14 17:13
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0054_project_default_reporting_period_duration'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='default_reporting_period_duration',
        ),
    ]
