# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-24 20:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0054_auto_20180224_1954'),
    ]

    operations = [
        migrations.CreateModel(
            name='VisitForContact',
            fields=[
                ('callforcontact_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='crm.CallForContact')),
                ('ref_call', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crm.Call', verbose_name='Reference Call')),
            ],
            options={
                'verbose_name': 'Visit',
                'verbose_name_plural': 'Visits',
            },
            bases=('crm.callforcontact',),
        ),
        migrations.AlterModelOptions(
            name='callforcontact',
            options={'verbose_name': 'Call', 'verbose_name_plural': 'Calls'},
        ),
    ]
