# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-24 20:39
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0055_auto_20180224_2002'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='visitforcontact',
            name='callforcontact_ptr',
        ),
        migrations.RemoveField(
            model_name='visitforcontact',
            name='ref_call',
        ),
        migrations.DeleteModel(
            name='VisitForContact',
        ),
    ]
