# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-08 17:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0060_attribute'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='attribute_set',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='crm.AttributeSet', verbose_name='Attribute Set'),
            preserve_default=False,
        ),
    ]
