# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-08 19:18
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0062_auto_20180408_1757'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productforcustomer',
            options={'verbose_name': 'Product', 'verbose_name_plural': 'Products'},
        ),
    ]
