# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-08 19:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0063_auto_20180408_1918'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attribute',
            name='attribute_set',
        ),
        migrations.AddField(
            model_name='attributeset',
            name='attributes',
            field=models.ManyToManyField(blank=True, to='crm.Attribute', verbose_name='Attributes'),
        ),
    ]
