# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-09 18:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0064_auto_20180408_1929'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductAttributeAssociation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(blank=True, max_length=255, null=True, verbose_name='Value')),
                ('attribute', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='related_attribute', to='crm.Attribute')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='related_product', to='crm.Product')),
            ],
            options={
                'verbose_name': 'Specific field',
                'verbose_name_plural': 'Specific fields',
            },
        ),
    ]
