# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-09 19:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0067_productforcustomer'),
    ]

    operations = [
        migrations.AddField(
            model_name='productforcustomer',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='crm.Product'),
        ),
    ]
