# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-15 16:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0068_productforcustomer_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='vatnumber',
            field=models.CharField(blank=True, max_length=20, verbose_name='Vat Number'),
        ),
        migrations.AddField(
            model_name='customer',
            name='isLead',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='productforcustomer',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='crm.Product', verbose_name='Related Product'),
        ),
    ]
