# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-10 09:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0070_auto_20180428_1619'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='role',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Role'),
        ),
    ]
