# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-10 15:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0071_auto_20180510_0929'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='prefix',
            field=models.CharField(blank=True, choices=[('F', 'Company'), ('W', 'Mrs'), ('H', 'Mr'), ('G', 'Ms'), ('J', 'J.D.'), ('A', 'Ar'), ('I', 'Ing'), ('D', 'Dott')], max_length=1, null=True, verbose_name='Prefix'),
        ),
        migrations.AlterField(
            model_name='postaladdress',
            name='prefix',
            field=models.CharField(blank=True, choices=[('F', 'Company'), ('W', 'Mrs'), ('H', 'Mr'), ('G', 'Ms'), ('J', 'J.D.'), ('A', 'Ar'), ('I', 'Ing'), ('D', 'Dott')], max_length=1, null=True, verbose_name='Prefix'),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_number',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Product Number'),
        ),
    ]
