# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-11 10:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0073_phonesystemforcustomer'),
    ]

    operations = [
        migrations.AddField(
            model_name='phonesystemforcustomer',
            name='maintainer',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Maintainer'),
        ),
        migrations.AlterField(
            model_name='phonesystemforcustomer',
            name='year',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Year of installation'),
        ),
    ]
