# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-19 15:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0074_auto_20180511_1005'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='phonesystemforcustomer',
            name='productforcustomer_ptr',
        ),
        migrations.DeleteModel(
            name='PhoneSystemForCustomer',
        ),
        migrations.CreateModel(
            name='AnalogPhoneForCustomer',
            fields=[
                ('productforcustomer_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='crm.ProductForCustomer')),
            ],
            options={
                'verbose_name': 'Analog Phone',
                'verbose_name_plural': 'Analog Phones',
            },
            bases=('crm.productforcustomer',),
        ),
        migrations.CreateModel(
            name='DigitalPhoneForCustomer',
            fields=[
                ('productforcustomer_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='crm.ProductForCustomer')),
            ],
            options={
                'verbose_name': 'Digital Phone',
                'verbose_name_plural': 'Digital Phones',
            },
            bases=('crm.productforcustomer',),
        ),
        migrations.CreateModel(
            name='InternetForCustomer',
            fields=[
                ('productforcustomer_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='crm.ProductForCustomer')),
            ],
            options={
                'verbose_name': 'Internet Connection',
                'verbose_name_plural': 'Internet Connections',
            },
            bases=('crm.productforcustomer',),
        ),
        migrations.CreateModel(
            name='MobileForCustomer',
            fields=[
                ('productforcustomer_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='crm.ProductForCustomer')),
            ],
            options={
                'verbose_name': 'Mobile Service',
                'verbose_name_plural': 'Mobile Services',
            },
            bases=('crm.productforcustomer',),
        ),
        migrations.CreateModel(
            name='SwitchboardForCustomer',
            fields=[
                ('productforcustomer_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='crm.ProductForCustomer')),
                ('internal_lines', models.IntegerField(blank=True, null=True, verbose_name='Internal lines')),
                ('external_lines', models.IntegerField(blank=True, null=True, verbose_name='External lines')),
            ],
            options={
                'verbose_name': 'Switchboard',
                'verbose_name_plural': 'Switchboards',
            },
            bases=('crm.productforcustomer',),
        ),
        migrations.AddField(
            model_name='productforcustomer',
            name='maintainer',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Maintainer'),
        ),
        migrations.AddField(
            model_name='productforcustomer',
            name='quantity',
            field=models.IntegerField(blank=True, null=True, verbose_name='Quantity'),
        ),
        migrations.AddField(
            model_name='productforcustomer',
            name='year',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Year of installation'),
        ),
    ]
