# Generated by Django 5.2.7 on 2026-04-12 18:17

import django.db.models.deletion
import filebrowser.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('crm', '0001_initial'),
        ('products', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=100, null=True, verbose_name='Title')),
                ('xsl_file', filebrowser.fields.FileBrowseField(max_length=200, verbose_name='XSL File')),
                ('fop_config_file', filebrowser.fields.FileBrowseField(blank=True, max_length=200, null=True, verbose_name='FOP Configuration File')),
                ('logo', filebrowser.fields.FileBrowseField(blank=True, max_length=200, null=True, verbose_name='Logo for the PDF generation')),
            ],
            options={
                'verbose_name': 'Document template',
                'verbose_name_plural': 'Document templates',
            },
        ),
        migrations.CreateModel(
            name='TemplateSet',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100, verbose_name='Title')),
            ],
            options={
                'verbose_name': 'Template-set',
                'verbose_name_plural': 'Template-sets',
            },
        ),
        migrations.CreateModel(
            name='BalanceSheetTemplate',
            fields=[
                ('documenttemplate_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='djangoUserExtension.documenttemplate')),
            ],
            options={
                'verbose_name': 'Balance sheet template',
                'verbose_name_plural': 'Balance sheet templates',
            },
            bases=('djangoUserExtension.documenttemplate',),
        ),
        migrations.CreateModel(
            name='DeliveryNoteTemplate',
            fields=[
                ('documenttemplate_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='djangoUserExtension.documenttemplate')),
            ],
            options={
                'verbose_name': 'Delivery note template',
                'verbose_name_plural': 'Delivery note templates',
            },
            bases=('djangoUserExtension.documenttemplate',),
        ),
        migrations.CreateModel(
            name='InvoiceTemplate',
            fields=[
                ('documenttemplate_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='djangoUserExtension.documenttemplate')),
            ],
            options={
                'verbose_name': 'Invoice template',
                'verbose_name_plural': 'Invoice templates',
            },
            bases=('djangoUserExtension.documenttemplate',),
        ),
        migrations.CreateModel(
            name='MonthlyProjectSummaryTemplate',
            fields=[
                ('documenttemplate_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='djangoUserExtension.documenttemplate')),
            ],
            options={
                'verbose_name': 'Monthly project summary template',
                'verbose_name_plural': 'Monthly project summary templates',
            },
            bases=('djangoUserExtension.documenttemplate',),
        ),
        migrations.CreateModel(
            name='PaymentReminderTemplate',
            fields=[
                ('documenttemplate_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='djangoUserExtension.documenttemplate')),
            ],
            options={
                'verbose_name': 'Payment reminder template',
                'verbose_name_plural': 'Payment reminder templates',
            },
            bases=('djangoUserExtension.documenttemplate',),
        ),
        migrations.CreateModel(
            name='ProfitLossStatementTemplate',
            fields=[
                ('documenttemplate_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='djangoUserExtension.documenttemplate')),
            ],
            options={
                'verbose_name': 'Profit loss statement template',
                'verbose_name_plural': 'Profit loss statement templates',
            },
            bases=('djangoUserExtension.documenttemplate',),
        ),
        migrations.CreateModel(
            name='PurchaseConfirmationTemplate',
            fields=[
                ('documenttemplate_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='djangoUserExtension.documenttemplate')),
            ],
            options={
                'verbose_name': 'Purchase confirmation template',
                'verbose_name_plural': 'Purchase confirmation templates',
            },
            bases=('djangoUserExtension.documenttemplate',),
        ),
        migrations.CreateModel(
            name='PurchaseOrderTemplate',
            fields=[
                ('documenttemplate_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='djangoUserExtension.documenttemplate')),
            ],
            options={
                'verbose_name': 'Purchase order template',
                'verbose_name_plural': 'Purchase order templates',
            },
            bases=('djangoUserExtension.documenttemplate',),
        ),
        migrations.CreateModel(
            name='QuoteTemplate',
            fields=[
                ('documenttemplate_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='djangoUserExtension.documenttemplate')),
            ],
            options={
                'verbose_name': 'Quote template',
                'verbose_name_plural': 'Quote templates',
            },
            bases=('djangoUserExtension.documenttemplate',),
        ),
        migrations.CreateModel(
            name='WorkReportTemplate',
            fields=[
                ('documenttemplate_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='djangoUserExtension.documenttemplate')),
            ],
            options={
                'verbose_name': 'Work report template',
                'verbose_name_plural': 'Work report templates',
            },
            bases=('djangoUserExtension.documenttemplate',),
        ),
        migrations.CreateModel(
            name='UserExtension',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('default_currency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.currency')),
                ('default_template_set', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='djangoUserExtension.templateset')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Extension',
                'verbose_name_plural': 'User Extension',
            },
        ),
        migrations.CreateModel(
            name='UserExtensionEmailAddress',
            fields=[
                ('emailaddress_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='crm.emailaddress')),
                ('purpose', models.CharField(choices=[('H', 'Private'), ('O', 'Business'), ('P', 'Mobile Private'), ('B', 'Mobile Business')], max_length=1, verbose_name='Purpose')),
                ('userExtension', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='djangoUserExtension.userextension')),
            ],
            options={
                'verbose_name': 'Email Address for User Extension',
                'verbose_name_plural': 'Email Address for User Extension',
            },
            bases=('crm.emailaddress',),
        ),
        migrations.CreateModel(
            name='UserExtensionPhoneAddress',
            fields=[
                ('phoneaddress_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='crm.phoneaddress')),
                ('purpose', models.CharField(choices=[('H', 'Private'), ('O', 'Business'), ('P', 'Mobile Private'), ('B', 'Mobile Business')], max_length=1, verbose_name='Purpose')),
                ('userExtension', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='djangoUserExtension.userextension')),
            ],
            options={
                'verbose_name': 'Phone number for User Extension',
                'verbose_name_plural': 'Phone number for User Extension',
            },
            bases=('crm.phoneaddress',),
        ),
        migrations.CreateModel(
            name='UserExtensionPostalAddress',
            fields=[
                ('postaladdress_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='crm.postaladdress')),
                ('purpose', models.CharField(choices=[('H', 'Private'), ('O', 'Business'), ('P', 'Mobile Private'), ('B', 'Mobile Business')], max_length=1, verbose_name='Purpose')),
                ('userExtension', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='djangoUserExtension.userextension')),
            ],
            options={
                'verbose_name': 'Postal Address for User Extension',
                'verbose_name_plural': 'Postal Address for User Extension',
            },
            bases=('crm.postaladdress',),
        ),
        migrations.AddField(
            model_name='templateset',
            name='balance_sheet_statement_template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='djangoUserExtension.balancesheettemplate'),
        ),
        migrations.AddField(
            model_name='templateset',
            name='delivery_note_template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='djangoUserExtension.deliverynotetemplate'),
        ),
        migrations.AddField(
            model_name='templateset',
            name='invoice_template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='djangoUserExtension.invoicetemplate'),
        ),
        migrations.AddField(
            model_name='templateset',
            name='monthly_project_summary_template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='djangoUserExtension.monthlyprojectsummarytemplate'),
        ),
        migrations.AddField(
            model_name='templateset',
            name='payment_reminder_template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='djangoUserExtension.paymentremindertemplate'),
        ),
        migrations.AddField(
            model_name='templateset',
            name='profit_loss_statement_template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='djangoUserExtension.profitlossstatementtemplate'),
        ),
        migrations.AddField(
            model_name='templateset',
            name='purchase_confirmation_template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='djangoUserExtension.purchaseconfirmationtemplate'),
        ),
        migrations.AddField(
            model_name='templateset',
            name='purchase_order_template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='djangoUserExtension.purchaseordertemplate'),
        ),
        migrations.AddField(
            model_name='templateset',
            name='quote_template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='djangoUserExtension.quotetemplate'),
        ),
        migrations.AddField(
            model_name='templateset',
            name='work_report_template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='djangoUserExtension.workreporttemplate'),
        ),
    ]
