# Generated by Django 5.2.13 on 2026-06-27 16:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('djangoUserExtension', '0005_user_address_assignments'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='despatchadvicetemplate',
            options={'verbose_name': 'Despatch advice template', 'verbose_name_plural': 'Despatch advice templates'},
        ),
        migrations.AlterModelOptions(
            name='quotationtemplate',
            options={'verbose_name': 'Quotation template', 'verbose_name_plural': 'Quotation templates'},
        ),
        migrations.AlterModelOptions(
            name='salesordertemplate',
            options={'verbose_name': 'Sales order template', 'verbose_name_plural': 'Sales order templates'},
        ),
    ]
