# Generated by Django 5.2.13 on 2026-06-27 16:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_drop_tax_accounting_fks'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='roleinworkspace',
            name='crm_riw_group_ws_idx',
        ),
        migrations.RenameIndex(
            model_name='workspaceswitchevent',
            new_name='crm_workspa_user_id_9cf2c2_idx',
            old_name='crm_wsswevent_user_ts_idx',
        ),
        migrations.AlterField(
            model_name='pdfexportprocess',
            name='workspace',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='core.workspace'),
        ),
        migrations.AlterField(
            model_name='roleinworkspace',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='workspace',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='workspaceswitchevent',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
