# Generated by Django 5.2.13 on 2026-07-04 16:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0008_remove_roleinworkspace_crm_riw_group_ws_idx_and_more"),
        ("products", "0009_alter_customergrouptransform_product_type_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="unittransform",
            name="product_type",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="products.product",
                verbose_name="Product",
            ),
        ),
    ]
