# Generated by Django 5.2.13 on 2026-08-22 20:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0010_pdfexportprocess_result_url_charfield"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="OidcTenant",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "alias",
                    models.CharField(
                        help_text="Short identifier used verbatim as the <tenantAlias> segment of oidc:<tenantAlias>:<name> group names.",
                        max_length=100,
                        unique=True,
                        verbose_name="Alias",
                    ),
                ),
                (
                    "issuer",
                    models.CharField(
                        help_text="The validated OIDC issuer URL this tenant is derived from.",
                        max_length=255,
                        unique=True,
                        verbose_name="Issuer",
                    ),
                ),
                (
                    "display_name",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Display Name"
                    ),
                ),
            ],
            options={
                "verbose_name": "OIDC Tenant",
                "verbose_name_plural": "OIDC Tenants",
                "db_table": "crm_oidctenant",
                "ordering": ["alias"],
            },
        ),
        migrations.CreateModel(
            name="ServiceAccountGrant",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created At"),
                ),
                (
                    "user",
                    models.OneToOneField(
                        help_text="The Django user this grant marks as an unrestricted service account.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="service_account_grant",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="User",
                    ),
                ),
            ],
            options={
                "verbose_name": "Service Account Grant",
                "verbose_name_plural": "Service Account Grants",
                "db_table": "crm_serviceaccountgrant",
                "ordering": ["-created_at"],
            },
        ),
    ]
