# -*- coding: utf-8 -*

from django.utils.translation import ugettext as trans

COUNTRIES = (
    ('AF', 'AFG', '004', trans('Afghanistan')),
    ('AX', 'ALA', '248', trans('Aland Islands')),
    ('AL', 'ALB', '008', trans('Albania')),
    ('DZ', 'DZA', '012', trans('Algeria')),
    ('AS', 'ASM', '016', trans('American Samoa')),
    ('AD', 'AND', '020', trans('Andorra')),
    ('AO', 'AGO', '024', trans('Angola')),
    ('AI', 'AIA', '660', trans('Anguilla')),
    ('AQ', 'ATA', '010', trans('Antarctica')),
    ('AG', 'ATG', '028', trans('Antigua and Barbuda')),
    ('AR', 'ARG', '032', trans('Argentina')),
    ('AM', 'ARM', '051', trans('Armenia')),
    ('AW', 'ABW', '533', trans('Aruba')),
    ('AU', 'AUS', '036', trans('Australia')),
    ('AT', 'AUT', '040', trans('Austria')),
    ('AZ', 'AZE', '031', trans('Azerbaijan')),
    ('BS', 'BHS', '044', trans('the Bahamas')),
    ('BH', 'BHR', '048', trans('Bahrain')),
    ('BD', 'BGD', '050', trans('Bangladesh')),
    ('BB', 'BRB', '052', trans('Barbados')),
    ('BY', 'BLR', '112', trans('Belarus')),
    ('BE', 'BEL', '056', trans('Belgium')),
    ('BZ', 'BLZ', '084', trans('Belize')),
    ('BJ', 'BEN', '204', trans('Benin')),
    ('BM', 'BMU', '060', trans('Bermuda')),
    ('BT', 'BTN', '064', trans('Bhutan')),
    ('BO', 'BOL', '068', trans('Bolivia')),
    ('BA', 'BIH', '070', trans('Bosnia and Herzegovina')),
    ('BW', 'BWA', '072', trans('Botswana')),
    ('BV', 'BVT', '074', trans('Bouvet Island')),
    ('BR', 'BRA', '076', trans('Brazil')),
    ('IO', 'IOT', '086', trans('British Indian Ocean Territory')),
    ('BN', 'BRN', '096', trans('Brunei Darussalam')),
    ('BG', 'BGR', '100', trans('Bulgaria')),
    ('BF', 'BFA', '854', trans('Burkina Faso')),
    ('BI', 'BDI', '108', trans('Burundi')),
    ('KH', 'KHM', '116', trans('Cambodia')),
    ('CM', 'CMR', '120', trans('Cameroon')),
    ('CA', 'CAN', '124', trans('Canada')),
    ('CV', 'CPV', '132', trans('Cape Verde')),
    ('KY', 'CYM', '136', trans('Cayman Islands')),
    ('CF', 'CAF', '140', trans('Central African Republic')),
    ('TD', 'TCD', '148', trans('Chad')),
    ('CL', 'CHL', '152', trans('Chile')),
    ('CN', 'CHN', '156', trans('China')),
    ('CX', 'CXR', '162', trans('Christmas Island')),
    ('CC', 'CCK', '166', trans('Cocos (Keeling) Islands')),
    ('CO', 'COL', '170', trans('Colombia')),
    ('KM', 'COM', '174', trans('Comoros')),
    ('CG', 'COG', '178', trans('Congo')),
    ('CD', 'COD', '180', trans('Democratic Republic of the Congo')),
    ('CK', 'COK', '184', trans('Cook Islands')),
    ('CR', 'CRI', '188', trans('Costa Rica')),
    ('CI', 'CIV', '384', trans('Cote d\'Ivoire')),
    ('HR', 'HRV', '191', trans('Croatia')),
    ('CU', 'CUB', '192', trans('Cuba')),
    ('CY', 'CYP', '196', trans('Cyprus')),
    ('CZ', 'CZE', '203', trans('Czech Republic')),
    ('DK', 'DNK', '208', trans('Denmark')),
    ('DJ', 'DJI', '262', trans('Djibouti')),
    ('DM', 'DMA', '212', trans('Dominica')),
    ('DO', 'DOM', '214', trans('Dominican Republic')),
    ('EC', 'ECU', '218', trans('Ecuador')),
    ('EG', 'EGY', '818', trans('Egypt')),
    ('SV', 'SLV', '222', trans('El Salvador')),
    ('GQ', 'GNQ', '226', trans('Equatorial Guinea')),
    ('ER', 'ERI', '232', trans('Eritrea')),
    ('EE', 'EST', '233', trans('Estonia')),
    ('ET', 'ETH', '231', trans('Ethiopia')),
    ('FK', 'FLK', '238', trans('Falkland Islands (Malvinas)')),
    ('FO', 'FRO', '234', trans('Faroe Islands')),
    ('FJ', 'FJI', '242', trans('Fiji')),
    ('FI', 'FIN', '246', trans('Finland')),
    ('FR', 'FRA', '250', trans('France')),
    ('GF', 'GUF', '254', trans('French Guiana')),
    ('PF', 'PYF', '258', trans('French Polynesia')),
    ('TF', 'ATF', '260', trans('French Southern and Antarctic Lands')),
    ('GA', 'GAB', '266', trans('Gabon')),
    ('GM', 'GMB', '270', trans('Gambia')),
    ('GE', 'GEO', '268', trans('Georgia')),
    ('DE', 'DEU', '276', trans('Germany')),
    ('GH', 'GHA', '288', trans('Ghana')),
    ('GI', 'GIB', '292', trans('Gibraltar')),
    ('GR', 'GRC', '300', trans('Greece')),
    ('GL', 'GRL', '304', trans('Greenland')),
    ('GD', 'GRD', '308', trans('Grenada')),
    ('GP', 'GLP', '312', trans('Guadeloupe')),
    ('GU', 'GUM', '316', trans('Guam')),
    ('GT', 'GTM', '320', trans('Guatemala')),
    ('GG', 'GGY', '831', trans('Guernsey')),
    ('GN', 'GIN', '324', trans('Guinea')),
    ('GW', 'GNB', '624', trans('Guinea-Bissau')),
    ('GY', 'GUY', '328', trans('Guyana')),
    ('HT', 'HTI', '332', trans('Haiti')),
    ('HM', 'HMD', '334', trans('Heard Island and McDonald Islands')),
    ('VA', 'VAT', '336', trans('Vatican City Holy See')),
    ('HN', 'HND', '340', trans('Honduras')),
    ('HK', 'HKG', '344', trans('Hong Kong')),
    ('HU', 'HUN', '348', trans('Hungary')),
    ('IS', 'ISL', '352', trans('Iceland')),
    ('IN', 'IND', '356', trans('India')),
    ('ID', 'IDN', '360', trans('Indonesia')),
    ('IR', 'IRN', '364', trans('Iran')),
    ('IQ', 'IRQ', '368', trans('Iraq')),
    ('IE', 'IRL', '372', trans('Ireland')),
    ('IM', 'IMN', '833', trans('Isle of Man')),
    ('IL', 'ISR', '376', trans('Israel')),
    ('IT', 'ITA', '380', trans('Italy')),
    ('JM', 'JAM', '388', trans('Jamaica')),
    ('JP', 'JPN', '392', trans('Japan')),
    ('JE', 'JEY', '832', trans('Jersey')),
    ('JO', 'JOR', '400', trans('Jordan')),
    ('KZ', 'KAZ', '398', trans('Kazakhstan')),
    ('KE', 'KEN', '404', trans('Kenya')),
    ('KI', 'KIR', '296', trans('Kiribati')),
    ('KP', 'PRK', '408', trans('North Korea')),
    ('KR', 'KOR', '410', trans('South Korea')),
    ('KW', 'KWT', '414', trans('Kuwait')),
    ('KG', 'KGZ', '417', trans('Kyrgyzstan')),
    ('LA', 'LAO', '418', trans('Laos Lao')),
    ('LV', 'LVA', '428', trans('Latvia')),
    ('LB', 'LBN', '422', trans('Lebanon')),
    ('LS', 'LSO', '426', trans('Lesotho')),
    ('LR', 'LBR', '430', trans('Liberia')),
    ('LY', 'LBY', '434', trans('Libya Libyan Arab Jamahiriya')),
    ('LI', 'LIE', '438', trans('Liechtenstein')),
    ('LT', 'LTU', '440', trans('Lithuania')),
    ('LU', 'LUX', '442', trans('Luxembourg')),
    ('MO', 'MAC', '446', trans('Macau Macao')),
    ('MK', 'MKD', '807', trans('Macedonia')),
    ('MG', 'MDG', '450', trans('Madagascar')),
    ('MW', 'MWI', '454', trans('Malawi')),
    ('MY', 'MYS', '458', trans('Malaysia')),
    ('MV', 'MDV', '462', trans('Maldives')),
    ('ML', 'MLI', '466', trans('Mali')),
    ('MT', 'MLT', '470', trans('Malta')),
    ('MH', 'MHL', '584', trans('Marshall Islands')),
    ('MQ', 'MTQ', '474', trans('Martinique')),
    ('MR', 'MRT', '478', trans('Mauritania')),
    ('MU', 'MUS', '480', trans('Mauritius')),
    ('YT', 'MYT', '175', trans('Mayotte')),
    ('MX', 'MEX', '484', trans('Mexico')),
    ('FM', 'FSM', '583', trans('Micronesia')),
    ('MD', 'MDA', '498', trans('Moldova')),
    ('MC', 'MCO', '492', trans('Monaco')),
    ('MN', 'MNG', '496', trans('Mongolia')),
    ('ME', 'MNE', '499', trans('Montenegro')),
    ('MS', 'MSR', '500', trans('Montserrat')),
    ('MA', 'MAR', '504', trans('Morocco')),
    ('MZ', 'MOZ', '508', trans('Mozambique')),
    ('MM', 'MMR', '104', trans('Myanmar')),
    ('NA', 'NAM', '516', trans('Namibia')),
    ('NR', 'NRU', '520', trans('Nauru')),
    ('NP', 'NPL', '524', trans('Nepal')),
    ('NL', 'NLD', '528', trans('Netherlands')),
    ('AN', 'ANT', '530', trans('Netherlands Antilles')),
    ('NC', 'NCL', '540', trans('New Caledonia')),
    ('NZ', 'NZL', '554', trans('New Zealand')),
    ('NI', 'NIC', '558', trans('Nicaragua')),
    ('NE', 'NER', '562', trans('Niger')),
    ('NG', 'NGA', '566', trans('Nigeria')),
    ('NU', 'NIU', '570', trans('Niue')),
    ('NF', 'NFK', '574', trans('Norfolk Island Norfolk Island')),
    ('MP', 'MNP', '580', trans('Northern Mariana Islands')),
    ('NO', 'NOR', '578', trans('Norway')),
    ('OM', 'OMN', '512', trans('Oman')),
    ('PK', 'PAK', '586', trans('Pakistan')),
    ('PW', 'PLW', '585', trans('Palau')),
    ('PS', 'PSE', '275', trans('Palestinian Territory')),
    ('PA', 'PAN', '591', trans('Panama')),
    ('PG', 'PNG', '598', trans('Papua New Guinea')),
    ('PY', 'PRY', '600', trans('Paraguay')),
    ('PE', 'PER', '604', trans('Peru')),
    ('PH', 'PHL', '608', trans('Philippines')),
    ('PN', 'PCN', '612', trans('Pitcairn Islands')),
    ('PL', 'POL', '616', trans('Poland')),
    ('PT', 'PRT', '620', trans('Portugal')),
    ('PR', 'PRI', '630', trans('Puerto Rico')),
    ('QA', 'QAT', '634', trans('Qatar')),
    ('RE', 'REU', '638', trans('Reunion')),
    ('RO', 'ROU', '642', trans('Romania')),
    ('RU', 'RUS', '643', trans('Russia')),
    ('RW', 'RWA', '646', trans('Rwanda')),
    ('SH', 'SHN', '654', trans('Saint Helena')),
    ('KN', 'KNA', '659', trans('Saint Kitts and Nevis')),
    ('LC', 'LCA', '662', trans('Saint Lucia')),
    ('PM', 'SPM', '666', trans('Saint Pierre and Miquelon')),
    ('VC', 'VCT', '670', trans('Saint Vincent and the Grenadines')),
    ('WS', 'WSM', '882', trans('Samoa')),
    ('SM', 'SMR', '674', trans('San Marino')),
    ('ST', 'STP', '678', trans('Sao Tome and Principe')),
    ('SA', 'SAU', '682', trans('Saudi Arabia')),
    ('SN', 'SEN', '686', trans('Senegal')),
    ('RS', 'SRB', '688', trans('Serbia')),
    ('SC', 'SYC', '690', trans('Seychelles')),
    ('SL', 'SLE', '694', trans('Sierra Leone')),
    ('SG', 'SGP', '702', trans('Singapore')),
    ('SK', 'SVK', '703', trans('Slovakia')),
    ('SI', 'SVN', '705', trans('Slovenia')),
    ('SB', 'SLB', '090', trans('Solomon Islands')),
    ('SO', 'SOM', '706', trans('Somalia')),
    ('ZA', 'ZAF', '710', trans('South Africa')),
    ('GS', 'SGS', '239', trans('South Georgia and the South Sandwich Islands')),
    ('ES', 'ESP', '724', trans('Spain')),
    ('LK', 'LKA', '144', trans('Sri Lanka')),
    ('SD', 'SDN', '736', trans('Sudan')),
    ('SR', 'SUR', '740', trans('Suriname')),
    ('SJ', 'SJM', '744', trans('Svalbard and Jan Mayen')),
    ('SZ', 'SWZ', '748', trans('Swaziland')),
    ('SE', 'SWE', '752', trans('Sweden')),
    ('CH', 'CHE', '756', trans('Switzerland')),
    ('SY', 'SYR', '760', trans('Syria')),
    ('TW', 'TWN', '158', trans('Taiwan')),
    ('TJ', 'TJK', '762', trans('Tajikistan')),
    ('TZ', 'TZA', '834', trans('Tanzania')),
    ('TH', 'THA', '764', trans('Thailand')),
    ('TL', 'TLS', '626', trans('East Timor')),
    ('TG', 'TGO', '768', trans('Togo')),
    ('TK', 'TKL', '772', trans('Tokelau')),
    ('TO', 'TON', '776', trans('Tonga')),
    ('TT', 'TTO', '780', trans('Trinidad and Tobago')),
    ('TN', 'TUN', '788', trans('Tunisia')),
    ('TR', 'TUR', '792', trans('Turkey')),
    ('TM', 'TKM', '795', trans('Turkmenistan')),
    ('TC', 'TCA', '796', trans('Turks and Caicos Islands')),
    ('TV', 'TUV', '798', trans('Tuvalu')),
    ('UG', 'UGA', '800', trans('Uganda')),
    ('UA', 'UKR', '804', trans('Ukraine')),
    ('AE', 'ARE', '784', trans('United Arab Emirates')),
    ('GB', 'GBR', '826', trans('United Kingdom')),
    ('US', 'USA', '840', trans('United States')),
    ('UM', 'UMI', '581', trans('United States Minor Outlying Islands')),
    ('UY', 'URY', '858', trans('Uruguay')),
    ('UZ', 'UZB', '860', trans('Uzbekistan')),
    ('VU', 'VUT', '548', trans('Vanuatu')),
    ('VE', 'VEN', '862', trans('Venezuela')),
    ('VN', 'VNM', '704', trans('Vietnam Viet Nam')),
    ('VG', 'VGB', '092', trans('British Virgin Islands')),
    ('VI', 'VIR', '850', trans('United States Virgin Islands')),
    ('WF', 'WLF', '876', trans('Wallis and Futuna')),
    ('EH', 'ESH', '732', trans('Western Sahara')),
    ('YE', 'YEM', '887', trans('Yemen')),
    ('ZM', 'ZMB', '894', trans('Zambia')),
    ('ZW', 'ZWE', '716', trans('Zimbabwe')),
)