# Generated by Django 5.2.7 on 2026-04-04 18:45
# Hand-edited to use SeparateDatabaseAndState for app split

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def update_content_types(apps, schema_editor):
    ContentType = apps.get_model('contenttypes', 'ContentType')
    models_to_move = [
        'contract', 'salesdocument', 'position', 'salesdocumentposition',
        'textparagraphinsalesdocument',
        'postaladdressforcontract', 'phoneaddressforcontract', 'emailaddressforcontract',
        'postaladdressforsalesdocument', 'phoneaddressforsalesdocument', 'emailaddressforsalesdocument',
        'invoice', 'quote', 'purchaseconfirmation', 'purchaseorder',
        'deliverynote', 'paymentreminder',
    ]
    for model_name in models_to_move:
        ContentType.objects.filter(
            app_label='crm', model=model_name
        ).update(app_label='contract_object_management')


def revert_content_types(apps, schema_editor):
    ContentType = apps.get_model('contenttypes', 'ContentType')
    models_to_move = [
        'contract', 'salesdocument', 'position', 'salesdocumentposition',
        'textparagraphinsalesdocument',
        'postaladdressforcontract', 'phoneaddressforcontract', 'emailaddressforcontract',
        'postaladdressforsalesdocument', 'phoneaddressforsalesdocument', 'emailaddressforsalesdocument',
        'invoice', 'quote', 'purchaseconfirmation', 'purchaseorder',
        'deliverynote', 'paymentreminder',
    ]
    for model_name in models_to_move:
        ContentType.objects.filter(
            app_label='contract_object_management', model=model_name
        ).update(app_label='crm')


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('crm', '0060_move_product_models_to_products_app'),
        ('djangoUserExtension', '0009_update_fk_to_products_app'),
        ('products', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
        migrations.CreateModel(
            name='SalesDocument',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('external_reference', models.CharField(blank=True, max_length=100, verbose_name='External Reference')),
                ('discount', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Discount')),
                ('description', models.CharField(blank=True, max_length=100, null=True, verbose_name='Description')),
                ('last_pricing_date', models.DateField(blank=True, null=True, verbose_name='Pricing Date')),
                ('last_calculated_price', models.DecimalField(blank=True, decimal_places=2, max_digits=17, null=True, verbose_name='Price without Tax ')),
                ('last_calculated_tax', models.DecimalField(blank=True, decimal_places=2, max_digits=17, null=True, verbose_name='Tax')),
                ('date_of_creation', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('custom_date_field', models.DateField(blank=True, null=True, verbose_name='Custom Date')),
                ('last_modification', models.DateTimeField(auto_now=True, verbose_name='Last modified')),
                ('last_print_date', models.DateTimeField(blank=True, null=True, verbose_name='Last printed')),
            ],
            options={
                'verbose_name': 'Sales Document',
                'verbose_name_plural': 'Sales Documents',
                'db_table': 'crm_salesdocument',
            },
        ),
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('position_number', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Position Number')),
                ('quantity', models.DecimalField(decimal_places=3, max_digits=10, verbose_name='Quantity')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('discount', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Discount')),
                ('sent_on', models.DateField(blank=True, null=True, verbose_name='Shipment on')),
                ('overwrite_product_price', models.BooleanField(verbose_name='Overwrite Product Price')),
                ('position_price_per_unit', models.DecimalField(blank=True, decimal_places=2, max_digits=17, null=True, verbose_name='Price Per Unit')),
                ('last_pricing_date', models.DateField(blank=True, null=True, verbose_name='Last Pricing Date')),
                ('last_calculated_price', models.DecimalField(blank=True, decimal_places=2, max_digits=17, null=True, verbose_name='Last Calculated Price')),
                ('last_calculated_tax', models.DecimalField(blank=True, decimal_places=2, max_digits=17, null=True, verbose_name='Last Calculated Tax')),
                ('product_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='products.producttype', verbose_name='Product')),
                ('unit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='products.unit', verbose_name='Unit')),
            ],
            options={
                'verbose_name': 'Position',
                'verbose_name_plural': 'Positions',
                'db_table': 'crm_position',
                'ordering': ['position_number'],
            },
        ),
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('description', models.TextField(verbose_name='Description')),
                ('date_of_creation', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('last_modification', models.DateTimeField(auto_now=True, verbose_name='Last modified')),
                ('default_currency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.currency', verbose_name='Default Currency')),
                ('default_customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='crm.customer', verbose_name='Default Customer')),
                ('default_supplier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='crm.supplier', verbose_name='Default Supplier')),
                ('default_template_set', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='djangoUserExtension.templateset', verbose_name='Default Template Set')),
                ('last_modified_by', models.ForeignKey(limit_choices_to={'is_staff': True}, on_delete=django.db.models.deletion.CASCADE, related_name='db_contractlstmodified', to=settings.AUTH_USER_MODEL, verbose_name='Last modified by')),
                ('staff', models.ForeignKey(blank=True, limit_choices_to={'is_staff': True}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='db_relcontractstaff', to=settings.AUTH_USER_MODEL, verbose_name='Staff')),
            ],
            options={
                'verbose_name': 'Contract',
                'verbose_name_plural': 'Contracts',
                'db_table': 'crm_contract',
            },
        ),
        migrations.CreateModel(
            name='DeliveryNote',
            fields=[
                ('salesdocument_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='contract_object_management.salesdocument')),
                ('tracking_reference', models.CharField(blank=True, max_length=100, verbose_name='Tracking Reference')),
                ('status', models.CharField(choices=[('C', 'Created'), ('S', 'Sent'), ('R', 'Received'), ('R', 'Lost')], max_length=1)),
            ],
            options={
                'verbose_name': 'Delivery Note',
                'verbose_name_plural': 'Delivery Notes',
                'db_table': 'crm_deliverynote',
            },
            bases=('contract_object_management.salesdocument',),
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('salesdocument_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='contract_object_management.salesdocument')),
                ('payable_until', models.DateField(verbose_name='To pay until')),
                ('payment_bank_reference', models.CharField(blank=True, max_length=100, null=True, verbose_name='Payment Bank Reference')),
                ('status', models.CharField(choices=[('P', 'Payed'), ('C', 'Invoice created'), ('I', 'Invoice sent'), ('F', 'First reminder sent'), ('R', 'Second reminder sent'), ('U', 'Customer cant pay'), ('D', 'Deleted')], max_length=1)),
            ],
            options={
                'verbose_name': 'Invoice',
                'verbose_name_plural': 'Invoices',
                'db_table': 'crm_invoice',
            },
            bases=('contract_object_management.salesdocument',),
        ),
        migrations.CreateModel(
            name='PaymentReminder',
            fields=[
                ('salesdocument_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='contract_object_management.salesdocument')),
                ('payable_until', models.DateField(verbose_name='To pay until')),
                ('payment_bank_reference', models.CharField(blank=True, max_length=100, null=True, verbose_name='Payment Bank Reference')),
                ('iteration_number', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(3)], verbose_name='Iteration Number')),
                ('status', models.CharField(choices=[('P', 'Payed'), ('C', 'Invoice created'), ('I', 'Invoice sent'), ('F', 'First reminder sent'), ('R', 'Second reminder sent'), ('U', 'Customer cant pay'), ('D', 'Deleted')], max_length=1)),
            ],
            options={
                'verbose_name': 'Payment Reminder',
                'verbose_name_plural': 'Payment Reminders',
                'db_table': 'crm_paymentreminder',
            },
            bases=('contract_object_management.salesdocument',),
        ),
        migrations.CreateModel(
            name='PurchaseConfirmation',
            fields=[
                ('salesdocument_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='contract_object_management.salesdocument')),
            ],
            options={
                'verbose_name': 'Purchase Confirmation',
                'verbose_name_plural': 'Purchase Confirmations',
                'db_table': 'crm_purchaseconfirmation',
            },
            bases=('contract_object_management.salesdocument',),
        ),
        migrations.CreateModel(
            name='Quote',
            fields=[
                ('salesdocument_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='contract_object_management.salesdocument')),
                ('valid_until', models.DateField(verbose_name='Valid until')),
                ('status', models.CharField(choices=[('S', 'Success'), ('I', 'Quote created'), ('Q', 'Quote sent'), ('F', 'First reminder sent'), ('R', 'Second reminder sent'), ('D', 'Deleted')], max_length=1, verbose_name='Status')),
            ],
            options={
                'verbose_name': 'Quote',
                'verbose_name_plural': 'Quotes',
                'db_table': 'crm_quote',
            },
            bases=('contract_object_management.salesdocument',),
        ),
        migrations.AddField(
            model_name='salesdocument',
            name='contract',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contract_object_management.contract', verbose_name='Contract'),
        ),
        migrations.AddField(
            model_name='salesdocument',
            name='currency',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.currency', verbose_name='Currency'),
        ),
        migrations.AddField(
            model_name='salesdocument',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crm.customer', verbose_name='Customer'),
        ),
        migrations.AddField(
            model_name='salesdocument',
            name='derived_from_sales_document',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contract_object_management.salesdocument'),
        ),
        migrations.AddField(
            model_name='salesdocument',
            name='last_modified_by',
            field=models.ForeignKey(blank='True', limit_choices_to={'is_staff': True}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='db_lstscmodified', to=settings.AUTH_USER_MODEL, verbose_name='Last modified by'),
        ),
        migrations.AddField(
            model_name='salesdocument',
            name='staff',
            field=models.ForeignKey(blank=True, limit_choices_to={'is_staff': True}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='db_relscstaff', to=settings.AUTH_USER_MODEL, verbose_name='Staff'),
        ),
        migrations.AddField(
            model_name='salesdocument',
            name='template_set',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='djangoUserExtension.documenttemplate', verbose_name='Referred Template'),
        ),
        migrations.CreateModel(
            name='EmailAddressForContract',
            fields=[
                ('emailaddress_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='crm.emailaddress')),
                ('purpose', models.CharField(choices=[('D', 'Delivery Address'), ('B', 'Billing Address'), ('C', 'Contact Address')], max_length=1, verbose_name='Purpose')),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contract_object_management.contract')),
            ],
            options={
                'verbose_name': 'Email Address For Contracts',
                'verbose_name_plural': 'Email Address For Contracts',
                'db_table': 'crm_emailaddressforcontract',
            },
            bases=('crm.emailaddress',),
        ),
        migrations.CreateModel(
            name='EmailAddressForSalesDocument',
            fields=[
                ('emailaddress_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='crm.emailaddress')),
                ('purpose', models.CharField(choices=[('D', 'Delivery Address'), ('B', 'Billing Address'), ('C', 'Contact Address')], max_length=1, verbose_name='Purpose')),
                ('sales_document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contract_object_management.salesdocument')),
            ],
            options={
                'verbose_name': 'Email Address For Sales Documents',
                'verbose_name_plural': 'Email Address For Sales Documents',
                'db_table': 'crm_emailaddressforsalesdocument',
            },
            bases=('crm.emailaddress',),
        ),
        migrations.CreateModel(
            name='PhoneAddressForContract',
            fields=[
                ('phoneaddress_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='crm.phoneaddress')),
                ('purpose', models.CharField(choices=[('D', 'Delivery Address'), ('B', 'Billing Address'), ('C', 'Contact Address')], max_length=1, verbose_name='Purpose')),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contract_object_management.contract')),
            ],
            options={
                'verbose_name': 'Phone Address For Contracts',
                'verbose_name_plural': 'Phone Address For Contracts',
                'db_table': 'crm_phoneaddressforcontract',
            },
            bases=('crm.phoneaddress',),
        ),
        migrations.CreateModel(
            name='PhoneAddressForSalesDocument',
            fields=[
                ('phoneaddress_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='crm.phoneaddress')),
                ('purpose', models.CharField(choices=[('D', 'Delivery Address'), ('B', 'Billing Address'), ('C', 'Contact Address')], max_length=1, verbose_name='Purpose')),
                ('sales_document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contract_object_management.salesdocument')),
            ],
            options={
                'verbose_name': 'Phone Address For Sales Documents',
                'verbose_name_plural': 'Phone Address For Sales Documents',
                'db_table': 'crm_phoneaddressforsalesdocument',
            },
            bases=('crm.phoneaddress',),
        ),
        migrations.CreateModel(
            name='PostalAddressForContract',
            fields=[
                ('postaladdress_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='crm.postaladdress')),
                ('purpose', models.CharField(choices=[('D', 'Delivery Address'), ('B', 'Billing Address'), ('C', 'Contact Address')], max_length=1, verbose_name='Purpose')),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contract_object_management.contract')),
            ],
            options={
                'verbose_name': 'Postal Address For Contracts',
                'verbose_name_plural': 'Postal Address For Contracts',
                'db_table': 'crm_postaladdressforcontract',
            },
            bases=('crm.postaladdress',),
        ),
        migrations.CreateModel(
            name='PostalAddressForSalesDocument',
            fields=[
                ('postaladdress_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='crm.postaladdress')),
                ('purpose', models.CharField(choices=[('D', 'Delivery Address'), ('B', 'Billing Address'), ('C', 'Contact Address')], max_length=1, verbose_name='Purpose')),
                ('sales_document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contract_object_management.salesdocument')),
            ],
            options={
                'verbose_name': 'Postal Address For Sales Documents',
                'verbose_name_plural': 'Postal Address For Sales Documents',
                'db_table': 'crm_postaladdressforsalesdocument',
            },
            bases=('crm.postaladdress',),
        ),
        migrations.CreateModel(
            name='TextParagraphInSalesDocument',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('purpose', models.CharField(choices=[('BS', 'Before subject'), ('AS', 'After subject'), ('BT', 'Before total'), ('AT', 'After total'), ('BW', 'Before wishes'), ('AW', 'After wishes'), ('C1', 'Custom 1'), ('C2', 'Custom 2'), ('C3', 'Custom 3'), ('C4', 'Custom 4')], max_length=2, verbose_name='Purpose')),
                ('text_paragraph', models.TextField(verbose_name='Text')),
                ('sales_document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contract_object_management.salesdocument')),
            ],
            options={
                'verbose_name': 'Text Paragraph In Sales Document',
                'verbose_name_plural': 'Text Paragraphs In Sales Documents',
                'db_table': 'crm_textparagraphinsalesdocument',
            },
        ),
        migrations.CreateModel(
            name='PurchaseOrder',
            fields=[
                ('salesdocument_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='contract_object_management.salesdocument')),
                ('status', models.CharField(choices=[('O', 'Ordered'), ('D', 'Delayed'), ('Y', 'Delivered'), ('I', 'Invoice registered'), ('P', 'Invoice payed')], max_length=1)),
                ('supplier', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='crm.supplier', verbose_name='Supplier')),
            ],
            options={
                'verbose_name': 'Purchase Order',
                'verbose_name_plural': 'Purchase Orders',
                'db_table': 'crm_purchaseorder',
            },
            bases=('contract_object_management.salesdocument',),
        ),
        migrations.CreateModel(
            name='SalesDocumentPosition',
            fields=[
                ('position_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='contract_object_management.position')),
                ('sales_document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contract_object_management.salesdocument', verbose_name='Contract')),
            ],
            options={
                'verbose_name': 'Position in Sales Document',
                'verbose_name_plural': 'Positions Sales Document',
                'db_table': 'crm_salesdocumentposition',
            },
            bases=('contract_object_management.position',),
        ),
            ],
            database_operations=[],
        ),
        migrations.RunPython(update_content_types, revert_content_types),
    ]
