# Generated by Django 5.2.7 on 2026-04-12 18:17

from django.db import migrations, models


from koalixcrm.migration_utils import CreateModelIfNotExists, AddFieldIfNotExists
class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        CreateModelIfNotExists(
            name='Contract',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('description', models.TextField(verbose_name='Description')),
                ('date_of_creation', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('last_modification', models.DateTimeField(auto_now=True, verbose_name='Last modified')),
            ],
            options={
                'verbose_name': 'Contract',
                'verbose_name_plural': 'Contracts',
                'db_table': 'crm_contract',
            },
        ),
        CreateModelIfNotExists(
            name='SalesDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_reference', models.CharField(blank=True, max_length=100, verbose_name='External Reference')),
                ('discount', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Discount')),
                ('description', models.CharField(blank=True, max_length=100, null=True, verbose_name='Description')),
                ('last_pricing_date', models.DateField(blank=True, null=True, verbose_name='Pricing Date')),
                ('last_calculated_price', models.DecimalField(blank=True, decimal_places=2, max_digits=17, null=True, verbose_name='Price without Tax ')),
                ('last_calculated_tax', models.DecimalField(blank=True, decimal_places=2, max_digits=17, null=True, verbose_name='Tax')),
                ('date_of_creation', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('custom_date_field', models.DateField(blank=True, null=True, verbose_name='Custom Date')),
                ('last_modification', models.DateTimeField(auto_now=True, verbose_name='Last modified')),
                ('last_print_date', models.DateTimeField(blank=True, null=True, verbose_name='Last printed')),
            ],
            options={
                'verbose_name': 'Sales Document',
                'verbose_name_plural': 'Sales Documents',
                'db_table': 'crm_salesdocument',
            },
        ),
    ]
