# Generated by Django 5.2.7 on 2026-04-12 18:17

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


from koalixcrm.migration_utils import CreateModelIfNotExists, AddFieldIfNotExists
class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contract_object_management', '0001_initial'),
        ('contacts', '0001_initial'),
        ('djangoUserExtension', '0001_initial'),
        ('products', '0001_initial'),
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        CreateModelIfNotExists(
            name='Position',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position_number', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Position Number')),
                ('quantity', models.DecimalField(decimal_places=3, max_digits=10, verbose_name='Quantity')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('discount', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Discount')),
                ('sent_on', models.DateField(blank=True, null=True, verbose_name='Shipment on')),
                ('overwrite_product_price', models.BooleanField(verbose_name='Overwrite Product Price')),
                ('position_price_per_unit', models.DecimalField(blank=True, decimal_places=2, max_digits=17, null=True, verbose_name='Price Per Unit')),
                ('last_pricing_date', models.DateField(blank=True, null=True, verbose_name='Last Pricing Date')),
                ('last_calculated_price', models.DecimalField(blank=True, decimal_places=2, max_digits=17, null=True, verbose_name='Last Calculated Price')),
                ('last_calculated_tax', models.DecimalField(blank=True, decimal_places=2, max_digits=17, null=True, verbose_name='Last Calculated Tax')),
                ('product_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='products.producttype', verbose_name='Product')),
                ('unit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.unit', verbose_name='Unit')),
            ],
            options={
                'verbose_name': 'Position',
                'verbose_name_plural': 'Positions',
                'db_table': 'crm_position',
                'ordering': ['position_number'],
            },
        ),
        AddFieldIfNotExists(
            model_name='contract',
            name='default_currency',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.currency', verbose_name='Default Currency'),
        ),
        AddFieldIfNotExists(
            model_name='contract',
            name='default_customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contacts.customer', verbose_name='Default Customer'),
        ),
        AddFieldIfNotExists(
            model_name='contract',
            name='default_supplier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contacts.supplier', verbose_name='Default Supplier'),
        ),
        AddFieldIfNotExists(
            model_name='contract',
            name='default_template_set',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='djangoUserExtension.templateset', verbose_name='Default Template Set'),
        ),
        AddFieldIfNotExists(
            model_name='contract',
            name='last_modified_by',
            field=models.ForeignKey(limit_choices_to={'is_staff': True}, on_delete=django.db.models.deletion.CASCADE, related_name='db_contractlstmodified', to=settings.AUTH_USER_MODEL, verbose_name='Last modified by'),
        ),
        AddFieldIfNotExists(
            model_name='contract',
            name='staff',
            field=models.ForeignKey(blank=True, limit_choices_to={'is_staff': True}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='db_relcontractstaff', to=settings.AUTH_USER_MODEL, verbose_name='Staff'),
        ),
        CreateModelIfNotExists(
            name='DeliveryNote',
            fields=[
                ('salesdocument_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='contract_object_management.salesdocument')),
                ('tracking_reference', models.CharField(blank=True, max_length=100, verbose_name='Tracking Reference')),
                ('status', models.CharField(choices=[('C', 'Created'), ('S', 'Sent'), ('R', 'Received'), ('R', 'Lost')], max_length=1)),
            ],
            options={
                'verbose_name': 'Delivery Note',
                'verbose_name_plural': 'Delivery Notes',
                'db_table': 'crm_deliverynote',
            },
            bases=('contract_object_management.salesdocument',),
        ),
        CreateModelIfNotExists(
            name='Invoice',
            fields=[
                ('salesdocument_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='contract_object_management.salesdocument')),
                ('payable_until', models.DateField(verbose_name='To pay until')),
                ('payment_bank_reference', models.CharField(blank=True, max_length=100, null=True, verbose_name='Payment Bank Reference')),
                ('status', models.CharField(choices=[('P', 'Payed'), ('C', 'Invoice created'), ('I', 'Invoice sent'), ('F', 'First reminder sent'), ('R', 'Second reminder sent'), ('U', 'Customer cant pay'), ('D', 'Deleted')], max_length=1)),
            ],
            options={
                'verbose_name': 'Invoice',
                'verbose_name_plural': 'Invoices',
                'db_table': 'crm_invoice',
            },
            bases=('contract_object_management.salesdocument',),
        ),
        CreateModelIfNotExists(
            name='PaymentReminder',
            fields=[
                ('salesdocument_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='contract_object_management.salesdocument')),
                ('payable_until', models.DateField(verbose_name='To pay until')),
                ('payment_bank_reference', models.CharField(blank=True, max_length=100, null=True, verbose_name='Payment Bank Reference')),
                ('iteration_number', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(3)], verbose_name='Iteration Number')),
                ('status', models.CharField(choices=[('P', 'Payed'), ('C', 'Invoice created'), ('I', 'Invoice sent'), ('F', 'First reminder sent'), ('R', 'Second reminder sent'), ('U', 'Customer cant pay'), ('D', 'Deleted')], max_length=1)),
            ],
            options={
                'verbose_name': 'Payment Reminder',
                'verbose_name_plural': 'Payment Reminders',
                'db_table': 'crm_paymentreminder',
            },
            bases=('contract_object_management.salesdocument',),
        ),
        CreateModelIfNotExists(
            name='PurchaseConfirmation',
            fields=[
                ('salesdocument_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='contract_object_management.salesdocument')),
            ],
            options={
                'verbose_name': 'Purchase Confirmation',
                'verbose_name_plural': 'Purchase Confirmations',
                'db_table': 'crm_purchaseconfirmation',
            },
            bases=('contract_object_management.salesdocument',),
        ),
        CreateModelIfNotExists(
            name='Quote',
            fields=[
                ('salesdocument_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='contract_object_management.salesdocument')),
                ('valid_until', models.DateField(verbose_name='Valid until')),
                ('status', models.CharField(choices=[('S', 'Success'), ('I', 'Quote created'), ('Q', 'Quote sent'), ('F', 'First reminder sent'), ('R', 'Second reminder sent'), ('D', 'Deleted')], max_length=1, verbose_name='Status')),
            ],
            options={
                'verbose_name': 'Quote',
                'verbose_name_plural': 'Quotes',
                'db_table': 'crm_quote',
            },
            bases=('contract_object_management.salesdocument',),
        ),
        AddFieldIfNotExists(
            model_name='salesdocument',
            name='contract',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contract_object_management.contract', verbose_name='Contract'),
        ),
        AddFieldIfNotExists(
            model_name='salesdocument',
            name='currency',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.currency', verbose_name='Currency'),
        ),
        AddFieldIfNotExists(
            model_name='salesdocument',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contacts.customer', verbose_name='Customer'),
        ),
        AddFieldIfNotExists(
            model_name='salesdocument',
            name='derived_from_sales_document',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contract_object_management.salesdocument'),
        ),
        AddFieldIfNotExists(
            model_name='salesdocument',
            name='last_modified_by',
            field=models.ForeignKey(blank='True', limit_choices_to={'is_staff': True}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='db_lstscmodified', to=settings.AUTH_USER_MODEL, verbose_name='Last modified by'),
        ),
        AddFieldIfNotExists(
            model_name='salesdocument',
            name='staff',
            field=models.ForeignKey(blank=True, limit_choices_to={'is_staff': True}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='db_relscstaff', to=settings.AUTH_USER_MODEL, verbose_name='Staff'),
        ),
        AddFieldIfNotExists(
            model_name='salesdocument',
            name='template_set',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='djangoUserExtension.documenttemplate', verbose_name='Referred Template'),
        ),
        CreateModelIfNotExists(
            name='EmailAddressForContract',
            fields=[
                ('emailaddress_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='contacts.emailaddress')),
                ('purpose', models.CharField(choices=[('D', 'Delivery Address'), ('B', 'Billing Address'), ('C', 'Contact Address')], max_length=1, verbose_name='Purpose')),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contract_object_management.contract')),
            ],
            options={
                'verbose_name': 'Email Address For Contracts',
                'verbose_name_plural': 'Email Address For Contracts',
                'db_table': 'crm_emailaddressforcontract',
            },
            bases=('contacts.emailaddress',),
        ),
        CreateModelIfNotExists(
            name='EmailAddressForSalesDocument',
            fields=[
                ('emailaddress_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='contacts.emailaddress')),
                ('purpose', models.CharField(choices=[('D', 'Delivery Address'), ('B', 'Billing Address'), ('C', 'Contact Address')], max_length=1, verbose_name='Purpose')),
                ('sales_document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contract_object_management.salesdocument')),
            ],
            options={
                'verbose_name': 'Email Address For Sales Documents',
                'verbose_name_plural': 'Email Address For Sales Documents',
                'db_table': 'crm_emailaddressforsalesdocument',
            },
            bases=('contacts.emailaddress',),
        ),
        CreateModelIfNotExists(
            name='PhoneAddressForContract',
            fields=[
                ('phoneaddress_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='contacts.phoneaddress')),
                ('purpose', models.CharField(choices=[('D', 'Delivery Address'), ('B', 'Billing Address'), ('C', 'Contact Address')], max_length=1, verbose_name='Purpose')),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contract_object_management.contract')),
            ],
            options={
                'verbose_name': 'Phone Address For Contracts',
                'verbose_name_plural': 'Phone Address For Contracts',
                'db_table': 'crm_phoneaddressforcontract',
            },
            bases=('contacts.phoneaddress',),
        ),
        CreateModelIfNotExists(
            name='PhoneAddressForSalesDocument',
            fields=[
                ('phoneaddress_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='contacts.phoneaddress')),
                ('purpose', models.CharField(choices=[('D', 'Delivery Address'), ('B', 'Billing Address'), ('C', 'Contact Address')], max_length=1, verbose_name='Purpose')),
                ('sales_document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contract_object_management.salesdocument')),
            ],
            options={
                'verbose_name': 'Phone Address For Sales Documents',
                'verbose_name_plural': 'Phone Address For Sales Documents',
                'db_table': 'crm_phoneaddressforsalesdocument',
            },
            bases=('contacts.phoneaddress',),
        ),
        CreateModelIfNotExists(
            name='PostalAddressForContract',
            fields=[
                ('postaladdress_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='contacts.postaladdress')),
                ('purpose', models.CharField(choices=[('D', 'Delivery Address'), ('B', 'Billing Address'), ('C', 'Contact Address')], max_length=1, verbose_name='Purpose')),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contract_object_management.contract')),
            ],
            options={
                'verbose_name': 'Postal Address For Contracts',
                'verbose_name_plural': 'Postal Address For Contracts',
                'db_table': 'crm_postaladdressforcontract',
            },
            bases=('contacts.postaladdress',),
        ),
        CreateModelIfNotExists(
            name='PostalAddressForSalesDocument',
            fields=[
                ('postaladdress_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='contacts.postaladdress')),
                ('purpose', models.CharField(choices=[('D', 'Delivery Address'), ('B', 'Billing Address'), ('C', 'Contact Address')], max_length=1, verbose_name='Purpose')),
                ('sales_document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contract_object_management.salesdocument')),
            ],
            options={
                'verbose_name': 'Postal Address For Sales Documents',
                'verbose_name_plural': 'Postal Address For Sales Documents',
                'db_table': 'crm_postaladdressforsalesdocument',
            },
            bases=('contacts.postaladdress',),
        ),
        CreateModelIfNotExists(
            name='TextParagraphInSalesDocument',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('purpose', models.CharField(choices=[('BS', 'Before subject'), ('AS', 'After subject'), ('BT', 'Before total'), ('AT', 'After total'), ('BW', 'Before wishes'), ('AW', 'After wishes'), ('C1', 'Custom 1'), ('C2', 'Custom 2'), ('C3', 'Custom 3'), ('C4', 'Custom 4')], max_length=2, verbose_name='Purpose')),
                ('text_paragraph', models.TextField(verbose_name='Text')),
                ('sales_document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contract_object_management.salesdocument')),
            ],
            options={
                'verbose_name': 'Text Paragraph In Sales Document',
                'verbose_name_plural': 'Text Paragraphs In Sales Documents',
                'db_table': 'crm_textparagraphinsalesdocument',
            },
        ),
        CreateModelIfNotExists(
            name='PurchaseOrder',
            fields=[
                ('salesdocument_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='contract_object_management.salesdocument')),
                ('status', models.CharField(choices=[('O', 'Ordered'), ('D', 'Delayed'), ('Y', 'Delivered'), ('I', 'Invoice registered'), ('P', 'Invoice payed')], max_length=1)),
                ('supplier', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='contacts.supplier', verbose_name='Supplier')),
            ],
            options={
                'verbose_name': 'Purchase Order',
                'verbose_name_plural': 'Purchase Orders',
                'db_table': 'crm_purchaseorder',
            },
            bases=('contract_object_management.salesdocument',),
        ),
        CreateModelIfNotExists(
            name='SalesDocumentPosition',
            fields=[
                ('position_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='contract_object_management.position')),
                ('sales_document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contract_object_management.salesdocument', verbose_name='Contract')),
            ],
            options={
                'verbose_name': 'Position in Sales Document',
                'verbose_name_plural': 'Positions Sales Document',
                'db_table': 'crm_salesdocumentposition',
            },
            bases=('contract_object_management.position',),
        ),
    ]
