# Generated by Django 5.2.7 on 2026-04-15 19:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contract_object_management', '0006_ubl_document_rename'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='commercialdocument',
            options={'verbose_name': 'Commercial Document', 'verbose_name_plural': 'Commercial Documents'},
        ),
        migrations.AlterModelOptions(
            name='commercialdocumentmedia',
            options={'ordering': ['-created_at'], 'verbose_name': 'Commercial Document Media', 'verbose_name_plural': 'Commercial Document Media'},
        ),
        migrations.AlterModelOptions(
            name='commercialdocumentposition',
            options={'verbose_name': 'Position in Commercial Document', 'verbose_name_plural': 'Positions Commercial Document'},
        ),
        migrations.AlterModelOptions(
            name='despatchadvice',
            options={'verbose_name': 'Despatch Advice', 'verbose_name_plural': 'Despatch Advices'},
        ),
        migrations.AlterModelOptions(
            name='emailaddressforcommercialdocument',
            options={'verbose_name': 'Email Address For Commercial Documents', 'verbose_name_plural': 'Email Address For Commercial Documents'},
        ),
        migrations.AlterModelOptions(
            name='phoneaddressforcommercialdocument',
            options={'verbose_name': 'Phone Address For Commercial Documents', 'verbose_name_plural': 'Phone Address For Commercial Documents'},
        ),
        migrations.AlterModelOptions(
            name='postaladdressforcommercialdocument',
            options={'verbose_name': 'Postal Address For Commercial Documents', 'verbose_name_plural': 'Postal Address For Commercial Documents'},
        ),
        migrations.AlterModelOptions(
            name='quotation',
            options={'verbose_name': 'Quotation', 'verbose_name_plural': 'Quotations'},
        ),
        migrations.AlterModelOptions(
            name='salesorder',
            options={'verbose_name': 'Sales Order', 'verbose_name_plural': 'Sales Orders'},
        ),
        migrations.AlterModelOptions(
            name='textparagraphincommercialdocument',
            options={'verbose_name': 'Text Paragraph In Commercial Document', 'verbose_name_plural': 'Text Paragraphs In Commercial Documents'},
        ),
        migrations.AlterField(
            model_name='commercialdocumentmedia',
            name='commercial_document',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media_files', to='contract_object_management.commercialdocument', verbose_name='Commercial Document'),
        ),
        migrations.AlterField(
            model_name='commercialdocumentmedia',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_commercial_document_media', to=settings.AUTH_USER_MODEL, verbose_name='Created By'),
        ),
        migrations.AlterField(
            model_name='quotation',
            name='status',
            field=models.CharField(choices=[('S', 'Success'), ('I', 'Quotation created'), ('Q', 'Quotation sent'), ('F', 'First reminder sent'), ('R', 'Second reminder sent'), ('D', 'Deleted')], max_length=1, verbose_name='Status'),
        ),
    ]
