# Generated by Django 5.2.13 on 2026-06-27 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contract_object_management', '0015_commercialdocument_field_renames'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commercialdocumentmedia',
            name='pdf_export_process',
        ),
        migrations.AlterField(
            model_name='textparagraphincommercialdocument',
            name='purpose',
            field=models.CharField(choices=[('BS', 'Before subject'), ('AS', 'After subject'), ('BT', 'Before total'), ('AT', 'After total'), ('BW', 'Before wishes'), ('AW', 'After wishes'), ('C1', 'Custom 1'), ('C2', 'Custom 2'), ('C3', 'Custom 3'), ('C4', 'Custom 4')], max_length=32, verbose_name='Purpose'),
        ),
    ]
