# Generated by Django 5.2.13 on 2026-07-04 16:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "contract_object_management",
            "0016_remove_commercialdocumentmedia_pdf_export_process_and_more",
        ),
        ("products", "0009_alter_customergrouptransform_product_type_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="position",
            name="product_type",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="products.product",
                verbose_name="Product",
            ),
        ),
    ]
