# Generated by Django 5.2.7 on 2026-04-12 18:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


from koalixcrm.migration_utils import CreateModelIfNotExists, AddFieldIfNotExists
class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('djangoUserExtension', '0001_initial'),
        ('products', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        CreateModelIfNotExists(
            name='AgreementStatus',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=250, verbose_name='Title')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Text')),
                ('is_agreed', models.BooleanField(verbose_name='Status represents agreement exists')),
            ],
            options={
                'verbose_name': 'Agreement Status',
                'verbose_name_plural': 'Agreement Status',
                'db_table': 'crm_agreementstatus',
            },
        ),
        CreateModelIfNotExists(
            name='AgreementType',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=300, verbose_name='Title')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Text')),
            ],
            options={
                'verbose_name': 'Agreement Type',
                'verbose_name_plural': 'Agreement Type',
                'db_table': 'crm_agreementtype',
            },
        ),
        CreateModelIfNotExists(
            name='EstimationStatus',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=250, verbose_name='Title')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Text')),
                ('is_obsolete', models.BooleanField(verbose_name='Status represents estimation is obsolete')),
            ],
            options={
                'verbose_name': 'Estimation Status',
                'verbose_name_plural': 'Estimation Status',
                'db_table': 'crm_estimationstatus',
            },
        ),
        CreateModelIfNotExists(
            name='Resource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'crm_resource',
            },
        ),
        CreateModelIfNotExists(
            name='ProjectLinkType',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=300, verbose_name='Title')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Text')),
            ],
            options={
                'verbose_name': 'Project Link Type',
                'verbose_name_plural': 'Project Link Type',
                'db_table': 'crm_projectlinktype',
            },
        ),
        CreateModelIfNotExists(
            name='ProjectStatus',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=250, verbose_name='Title')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Text')),
                ('is_done', models.BooleanField(verbose_name='Status represents project is done')),
            ],
            options={
                'verbose_name': 'Project Status',
                'verbose_name_plural': 'Project Status',
                'db_table': 'crm_projectstatus',
            },
        ),
        CreateModelIfNotExists(
            name='ReportingPeriodStatus',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=250, verbose_name='Title')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Text')),
                ('is_done', models.BooleanField(verbose_name='Status represents reporting period is closed')),
            ],
            options={
                'verbose_name': 'Reporting Period Status',
                'verbose_name_plural': 'Reporting Period Status',
                'db_table': 'crm_reportingperiodstatus',
            },
        ),
        CreateModelIfNotExists(
            name='ResourceType',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=300, verbose_name='Title')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Text')),
            ],
            options={
                'verbose_name': 'Resource Link Type',
                'verbose_name_plural': 'Resource Link Type',
                'db_table': 'crm_resourcetype',
            },
        ),
        CreateModelIfNotExists(
            name='TaskLinkType',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=300, verbose_name='Title')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Text')),
            ],
            options={
                'verbose_name': 'Task Link Type',
                'verbose_name_plural': 'Task Link Type',
                'db_table': 'crm_tasklinktype',
            },
        ),
        CreateModelIfNotExists(
            name='TaskStatus',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=250, verbose_name='Title')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Text')),
                ('is_done', models.BooleanField(verbose_name='Status represents task done')),
            ],
            options={
                'verbose_name': 'Task Status',
                'verbose_name_plural': 'Task Status',
                'db_table': 'crm_taskstatus',
            },
        ),
        CreateModelIfNotExists(
            name='HumanResource',
            fields=[
                ('resource_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='reporting.resource')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='djangoUserExtension.userextension', verbose_name='User')),
            ],
            options={
                'db_table': 'crm_humanresource',
            },
            bases=('reporting.resource',),
        ),
        CreateModelIfNotExists(
            name='Project',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('project_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Project name')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('date_of_creation', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('last_modification', models.DateTimeField(auto_now=True, verbose_name='Last modified')),
                ('default_currency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.currency', verbose_name='Default Currency')),
                ('default_template_set', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='djangoUserExtension.templateset', verbose_name='Default Template Set')),
                ('last_modified_by', models.ForeignKey(limit_choices_to={'is_staff': True}, on_delete=django.db.models.deletion.CASCADE, related_name='db_project_last_modified', to=settings.AUTH_USER_MODEL, verbose_name='Last modified by')),
                ('project_manager', models.ForeignKey(blank=True, limit_choices_to={'is_staff': True}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='db_rel_project_staff', to=settings.AUTH_USER_MODEL, verbose_name='Staff')),
                ('project_status', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='reporting.projectstatus', verbose_name='Project Status')),
            ],
            options={
                'verbose_name': 'Project',
                'verbose_name_plural': 'Projects',
                'db_table': 'crm_project',
            },
        ),
        CreateModelIfNotExists(
            name='GenericProjectLink',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('object_id', models.PositiveIntegerField()),
                ('date_of_creation', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('last_modified_by', models.ForeignKey(limit_choices_to={'is_staff': True}, on_delete=django.db.models.deletion.CASCADE, related_name='db_project_link_last_modified', to=settings.AUTH_USER_MODEL, verbose_name='Last modified by')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reporting.project', verbose_name='Project')),
                ('project_link_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='reporting.projectlinktype', verbose_name='Project Link Type')),
            ],
            options={
                'verbose_name': 'Project Link',
                'verbose_name_plural': 'Project Links',
                'db_table': 'crm_genericprojectlink',
            },
        ),
        CreateModelIfNotExists(
            name='ReportingPeriod',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200, verbose_name='Title')),
                ('begin', models.DateField(verbose_name='Begin')),
                ('end', models.DateField(verbose_name='End')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reporting.project', verbose_name='Project')),
                ('status', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='reporting.reportingperiodstatus', verbose_name='Reporting Period Status')),
            ],
            options={
                'verbose_name': 'Reporting Period',
                'verbose_name_plural': 'Reporting Periods',
                'db_table': 'crm_reportingperiod',
            },
        ),
        CreateModelIfNotExists(
            name='ResourceManager',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='djangoUserExtension.userextension', verbose_name='User')),
            ],
            options={
                'db_table': 'crm_resourcemanager',
            },
        ),
        AddFieldIfNotExists(
            model_name='resource',
            name='resource_manager',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='reporting.resourcemanager', verbose_name='Manager'),
        ),
        CreateModelIfNotExists(
            name='ResourcePrice',
            fields=[
                ('price_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='products.price')),
                ('resource', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reporting.resource', verbose_name='Resource')),
            ],
            options={
                'db_table': 'crm_resourceprice',
            },
            bases=('products.price',),
        ),
        AddFieldIfNotExists(
            model_name='resource',
            name='resource_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='reporting.resourcetype', verbose_name='Resource Type'),
        ),
        CreateModelIfNotExists(
            name='Task',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, max_length=100, null=True, verbose_name='Title')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('last_status_change', models.DateField(blank=True, verbose_name='Last Status Change')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='reporting.project', verbose_name='Project')),
                ('status', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='reporting.taskstatus', verbose_name='Status')),
            ],
            options={
                'verbose_name': 'Task',
                'verbose_name_plural': 'Tasks',
                'db_table': 'crm_task',
            },
        ),
        CreateModelIfNotExists(
            name='Estimation',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('date_from', models.DateField(verbose_name='Estimation From')),
                ('date_until', models.DateField(verbose_name='Estimation Until')),
                ('amount', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Amount')),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reporting.estimationstatus', verbose_name='Status of the estimation')),
                ('resource', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reporting.resource')),
                ('reporting_period', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reporting.reportingperiod', verbose_name='Reporting Period based on which the estimation was done')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reporting.task', verbose_name='Task')),
            ],
            options={
                'verbose_name': 'Estimation of Resource Consumption',
                'verbose_name_plural': 'Estimation of Resource Consumptions',
                'db_table': 'crm_estimation',
            },
        ),
        CreateModelIfNotExists(
            name='Agreement',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('date_from', models.DateField(verbose_name='Agreement From')),
                ('date_until', models.DateField(verbose_name='Agreement To')),
                ('amount', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Amount')),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.unit')),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reporting.agreementstatus')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reporting.agreementtype')),
                ('resource', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reporting.resource')),
                ('costs', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reporting.resourceprice')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reporting.task', verbose_name='Task')),
            ],
            options={
                'verbose_name': 'Agreement',
                'verbose_name_plural': 'Agreements',
                'db_table': 'crm_agreement',
            },
        ),
        CreateModelIfNotExists(
            name='GenericTaskLink',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('object_id', models.PositiveIntegerField()),
                ('date_of_creation', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('last_modified_by', models.ForeignKey(limit_choices_to={'is_staff': True}, on_delete=django.db.models.deletion.CASCADE, related_name='db_task_link_last_modified', to=settings.AUTH_USER_MODEL, verbose_name='Last modified by')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reporting.task', verbose_name='Task')),
                ('task_link_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='reporting.tasklinktype', verbose_name='Task Link Type')),
            ],
            options={
                'verbose_name': 'Task Link',
                'verbose_name_plural': 'Task Links',
                'db_table': 'crm_generictasklink',
            },
        ),
        CreateModelIfNotExists(
            name='Work',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('date', models.DateField(verbose_name='Date')),
                ('start_time', models.DateTimeField(blank=True, null=True, verbose_name='Start Time')),
                ('stop_time', models.DateTimeField(blank=True, null=True, verbose_name='Stop Time')),
                ('worked_hours', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Worked Hours')),
                ('short_description', models.CharField(max_length=300, verbose_name='Short Description')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Text')),
                ('reporting_period', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reporting.reportingperiod', verbose_name='Reporting Period')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reporting.task', verbose_name='Task')),
                ('human_resource', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reporting.humanresource')),
            ],
            options={
                'verbose_name': 'Work',
                'verbose_name_plural': 'Work',
                'db_table': 'crm_work',
            },
        ),
    ]
